# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 22:54:58

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new alleventsView { win.show() } 
		exec()
	}
}

class alleventsView from WindowsViewParent
	win = new qMainWindow() { 
		move(49,67)
		resize(400,400)
		setWindowTitle("All Events")
		setstylesheet("background-color:;") 
		AllEvents1 = new qallevents(win) {
			setKeyPressEvent("")
			setMouseButtonPressEvent(Method(:clickonwindow))
			setMouseButtonReleaseEvent("")
			setMouseButtonDblClickEvent("")
			setMouseMoveEvent("")
			setCloseEvent("")
			setContextMenuEvent("")
			setDragEnterEvent("")
			setDragLeaveEvent("")
			setDragMoveEvent("")
			setDropEvent("")
			setEnterEvent("")
			setFocusInEvent("")
			setFocusOutEvent("")
			setKeyReleaseEvent("")
			setLeaveEvent("")
			setNonClientAreaMouseButtonDblClickEvent("")
			setNonClientAreaMouseButtonPressEvent("")
			setNonClientAreaMouseButtonReleaseEvent("")
			setNonClientAreaMouseMoveEvent("")
			setMoveEvent("")
			setResizeEvent("")
			setWindowActivateEvent("")
			setWindowBlockedEvent("")
			setWindowDeactivateEvent("")
			setWindowStateChangeEvent("")
			setWindowUnblockedEvent("")
			setPaintEvent("")
			
		}
		win.installEventFilter(AllEvents1)
	}

# End of the Generated Source Code File...