# The Ring Standard Library
# Trace Library
# 2016-2017, Mahmoud Fayed <msfclipper@yahoo.com>

# Trace Events
TRACEEVENT_NEWLINE 			= 1
TRACEEVENT_NEWFUNC 		= 2
TRACEEVENT_RETURN 			= 3
TRACEEVENT_ERROR 				= 4
TRACEEVENT_BEFORECFUNC 	= 5
TRACEEVENT_AFTERCFUNC 	= 6

# Trace Data
TRACEDATA_LINENUMBER  = 1
TRACEDATA_FILENAME 		= 2
TRACEDATA_FUNCNAME 	= 3
TRACEDATA_METHODORFUNC = 4

