# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 06/05/2017
# Time : 08:29:42

Load "stdlib.ring"
Load "guilib.ring"

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new secondwindowView { win.show() } 
		exec()
	}
}

class secondwindowView from WindowsViewParent
	win = new qMainWindow() { 
		move(111,91)
		resize(400,400)
		setWindowTitle("The Second Window")
		setstylesheet("background-color:#00007f;") 
		Button1 = new qpushbutton(win) {
			move(56,81)
			resize(277,61)
			setstylesheet("color:black;background-color:#ffff7f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,16,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			setText("Close Window")
			setClickEvent(Method(:CloseWindow))
			setBtnImage(Button1,"")
			
		}
		Label1 = new qlabel(win) {
			move(57,181)
			resize(279,56)
			setstylesheet("color:#ffffff;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		Button3 = new qpushbutton(win) {
			move(58,255)
			resize(277,61)
			setstylesheet("color:black;background-color:#ffff7f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,16,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			setText("Message to First Window")
			setClickEvent(Method(:sendMessage))
			setBtnImage(Button3,"")
			
		}
	}

# End of the Generated Source Code File...