#=====================================================#
# Citations Prediction Application
# 2022, Mahmoud Fayed <msfclipper@yahoo.com>
# Form/Window Controller - Source Code File
#=====================================================#

aDataList = [
	[
		"AU",
		"TI",
		"AB",
		"TC"
	],
	[
		"Hall-Stoodley, Luanne Hu, Fen Ze Gieseke, Armin Nistico, Laura Nguyen, Duc Hayes, Jay Forbes, Michael Greenberg, David P. Dice, Bethany Burrows, Amy Wackym, P. Ashley Stoodley, Paul Post, J. Christopher Ehrlich, Garth D. Kerschner, Joseph E.",
		"Direct detection of bacterial Biofilms on the middle-ear mucosa of children with chronic otitis media",
		"Context Chronic otitis media ( OM) is a common pediatric infectious disease. Previous studies demonstrating that metabolically active bacteria exist in culture-negative pediatric middle-ear effusions and that experimental infection with Haemophilus influenzae in the chinchilla model of otitis media results in the formation of adherent mucosal biofilms suggest that chronic OM may result from a mucosal biofilm infection.Objective To test the hypothesis that chronic OM in humans is biofilm-related.Design, Setting, and Patients Middle-ear mucosa (MEM) biopsy specimens were obtained from 26 children ( mean age, 2.5 [ range, 0.5-14] years) undergoing tympanostomy tube placement for treatment of otitis media with effusion (OME) and recurrent OM and were analyzed using microbiological culture, polymerase chain reaction (PCR)based diagnostics, direct microscopic examination, fluorescence in situ hybridization, and immunostaining. Uninfected ( control) MEM specimens were obtained from 3 children and 5 adults undergoing cochlear implantation. Patients were enrolled between February 2004 and April 2005 from a single US tertiary referral otolaryngology practice.Main Outcome Measures Confocal laser scanning microscopic (CLSM) images were obtained from MEM biopsy specimens and were evaluated for biofilm morphology using generic stains and species-specific probes for H influenzae, Streptococcus pneumoniae, and Moraxella catarrhalis. Effusions, when present, were evaluated by PCR and culture for evidence of pathogen-specific nucleic acid sequences and bacterial growth, respectively.Results Of the 26 children undergoing tympanostomy tube placement, 13 (50%) had OME, 20 (77%) had recurrent OM, and 7 (27%) had both diagnoses; 27 of 52 (52%) of the ears had effusions, 24 of 24 effusions were PCR-positive for at least 1 OM pathogen, and 6 (22%) of 27 effusions were culture-positive for any pathogen. Mucosal biofilms were visualized by CLSM on 46 (92%) of 50 MEM specimens from children with OME and recurrent OM using generic and pathogen-specific probes. Biofilms were not observed on 8 control MEM specimens obtained from the patients undergoing cochlear implantation.Conclusion Direct detection of biofilms on MEM biopsy specimens from children with OME and recurrent OM supports the hypothesis that these chronic middle-ear disorders are biofilmrelated."+char(34)+"",
		579
	],
	[
		"Gates, GA Mills, JH",
		"Presbycusis",
		"The inevitable deterioration in hearing ability that occurs with age-presbycusis-is a multifactorial process that can vary in severity from mild to substantial. Left untreated, presbycusis of a moderate or greater degree affects communication and can contribute to isolation, depression, and, possibly, dementia. These psychological effects are largely reversible with rehabilitative treatment. Comprehensive rehabilitation is widely available but underused because, in part, of social attitudes that undervalue hearing, in addition to the cost and stigma of hearing aids. Remediation of presbycusis is an important contributor to quality of life in geriatric medicine and can include education about communication effectiveness, hearing aids, assistive listening devices, and cochlear implants for severe hearing loss. Primary care physicians should screen and refer their elderly patients for assessment and remediation. Where hearing aids no longer provide benefit, cochlear implantation is the treatment of choice with excellent results even in octogenarians."+char(34)+"",
		514
	],
	[
		"Niparko, John K. Tobey, Emily A. Thal, Donna J. Eisenberg, Laurie S. Wang, Nae-Yuh Quittner, Alexandra L. Fink, Nancy E.",
		"Spoken Language Development in Children Following Cochlear Implantation",
		"Context Cochlear implantation is a surgical alternative to traditional amplification (hearing aids) that can facilitate spoken language development in young children with severe to profound sensorineural hearing loss (SNHL).Objective To prospectively assess spoken language acquisition following cochlear implantation in young children.Design, Setting, and Participants Prospective, longitudinal, and multidimensional assessment of spoken language development over a 3-year period in children who underwent cochlear implantation before 5 years of age (n=188) from 6 US centers and hearing children of similar ages (n=97) from 2 preschools recruited between November 2002 and December 2004. Follow-up completed between November 2005 and May 2008.Main Outcome Measures Performance on measures of spoken language comprehension and expression (Reynell Developmental Language Scales).Results Children undergoing cochlear implantation showed greater improvement in spoken language performance (10.4; 95% confidence interval [CI], 9.6-11.2 points per year in comprehension; 8.4; 95% CI, 7.8-9.0 in expression) than would be predicted by their preimplantation baseline scores (5.4; 95% CI, 4.1-6.7, comprehension; 5.8; 95% CI, 4.6-7.0, expression), although mean scores were not restored to age-appropriate levels after 3 years. Younger age at cochlear implantation was associated with significantly steeper rate increases in comprehension (1.1; 95% CI, 0.5-1.7 points per year younger) and expression (1.0; 95% CI, 0.6-1.5 points per year younger). Similarly, each 1-year shorter history of hearing deficit was associated with steeper rate increases in comprehension (0.8; 95% CI, 0.2-1.2 points per year shorter) and expression (0.6; 95% CI, 0.2-1.0 points per year shorter). In multivariable analyses, greater residual hearing prior to cochlear implantation, higher ratings of parent-child interactions, and higher socioeconomic status were associated with greater rates of improvement in comprehension and expression.Conclusion The use of cochlear implants in young children was associated with better spoken language learning than would be predicted from their preimplantation scores. JAMA. 2010;303(15):1498-1506 www.jama.com"+char(34)+"",
		468
	]
]