ASSERT_CRASH        You can't continue with the program running.
ASSERT_INFO         The program can continue in UNSECURED WAY. It's possible that the results now will be incorrect or data loss occurs.
CONTACT_INFO        For more information about this incident, please contact with:
FILE_TEXT			File
LINE_TEXT			Line
SHOW_ASSERT         Show this window in next assert.
ASSERT_LOG          Write assert info in log.
ASSERT_TITLE        %s ran into a problem
DEBUG_TEXT			Debug
CONTINUE_TEXT		Continue
EXIT_TEXT			Exit

