# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 06/05/2017
# Time : 07:08:04

Load "stdlib.ring"
Load "guilib.ring"

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new labelandbuttoncolorsView { win.show() } 
		exec()
	}
}

class labelandbuttoncolorsView from WindowsViewParent
	win = new qMainWindow() { 
		move(39,79)
		resize(400,280)
		setWindowTitle("Label and Button Colors")
		setstylesheet("background-color:;") 
		Label1 = new qlabel(win) {
			move(37,32)
			resize(311,66)
			setstylesheet("color:#00007f;background-color:#00ff7f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			setText("Hello, World!")
			setAlignment(Qt_AlignHCenter |  Qt_AlignVCenter)
		}
		Button1 = new qpushbutton(win) {
			move(112,154)
			resize(158,43)
			setstylesheet("color:black;background-color:#ffff00;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,16,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			setText("Close")
			setClickEvent(Method(:CloseWindow))
			setBtnImage(Button1,"")
			
		}
	}

# End of the Generated Source Code File...