# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 06/05/2017
# Time : 07:31:43

Load "stdlib.ring"
Load "guilib.ring"

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new sumtwonumbersView { win.show() } 
		exec()
	}
}

class sumtwonumbersView from WindowsViewParent
	win = new qMainWindow() { 
		move(27,69)
		resize(457,272)
		setWindowTitle("Sum Two Numbers")
		setstylesheet("background-color:;") 
		Label1 = new qlabel(win) {
			move(18,44)
			resize(141,31)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("The First Number")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		LineEdit1 = new qlineedit(win) {
			move(171,36)
			resize(260,43)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Label2 = new qlabel(win) {
			move(18,103)
			resize(141,31)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("The Second Number")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		LineEdit2 = new qlineedit(win) {
			move(171,95)
			resize(260,43)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		LineEdit3 = new qlineedit(win) {
			move(171,165)
			resize(260,43)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Button4 = new qpushbutton(win) {
			move(28,163)
			resize(131,40)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Sum")
			setClickEvent(Method(:SumNumbers))
			setBtnImage(Button4,"")
			
		}
	}

# End of the Generated Source Code File...