# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 22:58:23

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new statusbarView { win.show() } 
		exec()
	}
}

class statusbarView from WindowsViewParent
	win = new qMainWindow() { 
		move(35,73)
		resize(400,400)
		setWindowTitle("Using Statusbar")
		setstylesheet("background-color:;") 
		Statusbar1 = new statusbar(win) {
			move(5,309)
			resize(193,24)
			setstylesheet("color:#ffffff;background-color:#00007f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			ShowMessage("Ready",0)
			win.setStatusBar(Statusbar1)
		}
	}

# End of the Generated Source Code File...