#================================================#
# This code is generated by Bing Chat (AI)
# Questions by Fayed
#================================================#

p = new Person("Alice" , 25)

? p.name # prints Alice
? p.age # prints 25

class Person

    name = ""
    age = 0

    func init(name , age)
        self.name = name
        self.age = age
    end

end