#================================================#
# This code is generated by Bing Chat (AI)
# Questions by Fayed
#================================================#

# Call the functions
one()
two()
three()
four()
five()

# Define the functions
func one
    see "one\n"

func two
    see "two\n"

func three
    see "three\n"

func four
    see "four\n"

func five
    see "five\n"