call ring scripts/s28.ring
call ring scripts/s60.ring
call ring scripts/s61.ring
call ring scripts/s62.ring
call ring scripts/s63.ring
call ring scripts/s64.ring
call ring scripts/s65.ring
call ring scripts/s78.ring < scripts/test78.txt
call ring scripts/oop.ring
call ring scripts/oop2.ring
call ring scripts/oop3.ring
call ring scripts/oop4.ring
call ring scripts/oop5.ring
call ring scripts/oop6.ring
call ring scripts/oop7.ring
call ring scripts/oop8.ring
call ring scripts/oop9.ring
call ring scripts/oop10.ring
call ring scripts/oop11.ring
call ring scripts/oop12.ring
call ring scripts/oop13.ring
call ring scripts/oop14.ring
call ring scripts/oop15.ring
call ring scripts/oop16.ring
call ring scripts/oop17.ring
call ring scripts/oop18.ring
call ring scripts/oop19.ring
call ring scripts/oop20.ring
call ring scripts/oop21.ring
call ring scripts/oop22.ring
call ring scripts/oop23.ring
call ring scripts/oop24.ring
call ring scripts/oop25.ring
call ring scripts/oop26.ring
call ring scripts/oop27.ring
call ring scripts/oop28.ring
call ring scripts/oop29.ring
call ring scripts/oop30.ring
call ring scripts/oop31.ring
call ring scripts/oop32.ring
call ring scripts/oop33.ring
call ring scripts/oop34.ring
call ring scripts/oop35.ring
call ring scripts/oop36.ring
call ring scripts/oop37.ring
call ring scripts/oop38.ring
call ring scripts/oop39.ring
call ring scripts/oop40.ring
call ring scripts/oop41.ring
call ring scripts/oop42.ring
call ring scripts/oop43.ring
call ring scripts/oop44.ring
call ring scripts/oop45.ring
call ring scripts/oop46.ring
call ring scripts/selfbug.ring
call ring scripts/selfininit.ring
call ring scripts/subobjs.ring
call ring scripts/subobjs2.ring
call ring scripts/subobjs3.ring
call ring scripts/subobjs4.ring
call ring scripts/subobjs5.ring
call ring scripts/newinlist.ring
call ring scripts/toop1.ring
call ring scripts/toop2.ring
call ring scripts/toop3.ring
call ring scripts/toop4.ring
call ring scripts/toop5.ring
call ring scripts/toop6.ring
call ring scripts/toop7.ring
call ring scripts/toop8.ring
call ring scripts/toop9.ring
call ring scripts/toop10.ring
call ring scripts/toop11.ring
call ring scripts/string2.ring
call ring scripts/comment.ring
call ring scripts/commenterror.ring
call ring scripts/passbug.ring
call ring scripts/passbug2.ring
call ring scripts/passbug3.ring
call ring scripts/retbug.ring
call ring scripts/privatebug.ring
call ring scripts/privatebug2.ring
call ring scripts/privatebug3.ring
call ring scripts/sort.ring
call ring scripts/sort2.ring
call ring scripts/sort3.ring
call ring scripts/emptyfile.ring
call ring scripts/emptyfile2.ring
call ring scripts/emptyfile3.ring
call ring scripts/emptyfile4.ring
call ring scripts/evaltest.ring
call ring scripts/evalclassbug.ring
call ring scripts/evalmem2.ring
call ring scripts/evalscope.ring
call ring scripts/braceend.ring
call ring scripts/braceend2.ring
call ring scripts/bitwise.ring
call ring scripts/retineval.ring
call ring scripts/retfunc.ring
call ring scripts/math.ring
call ring scripts/newinmethodpara.ring
call ring scripts/newinpara.ring
call ring scripts/findcrash.ring
call ring scripts/initbrace.ring
call ring scripts/callinitmethod.ring
call ring scripts/callinitmethod2.ring
call ring scripts/callinitmethod3.ring
call ring scripts/callmethodfromobj.ring
call ring scripts/braceerror2.ring
call ring scripts/parabracebug.ring
call ring scripts/dotbracebug.ring
call ring scripts/trybug.ring
call ring scripts/forincrash.ring
call ring scripts/forinlist.ring
call ring scripts/timeforfun.ring
call ring scripts/printobj2.ring
call ring scripts/insertfirst.ring
call ring scripts/ppcrash.ring
call ring scripts/ppcrash2.ring
call ring scripts/nestednew3.ring
call ring scripts/each.ring
call ring scripts/retassign.ring
call ring scripts/forinstr.ring
call ring scripts/happynum.ring
call ring scripts/happynum2.ring
call ring scripts/addmethod.ring
call ring scripts/addmethod2.ring
