call ring scripts/s28.ring
call ring scripts/s60.ring
call ring scripts/s61.ring
call ring scripts/s62.ring
call ring scripts/s63.ring
call ring scripts/s64.ring
call ring scripts/s65.ring
call ring scripts/s78.ring < scripts/test78.txt
call ring scripts/oop.ring
call ring scripts/oop2.ring
call ring scripts/oop3.ring
call ring scripts/oop4.ring
call ring scripts/oop5.ring
call ring scripts/oop6.ring
call ring scripts/oop7.ring
call ring scripts/oop8.ring
call ring scripts/oop9.ring
call ring scripts/oop10.ring
call ring scripts/oop11.ring
call ring scripts/oop12.ring
call ring scripts/oop13.ring
call ring scripts/oop14.ring
call ring scripts/oop15.ring
call ring scripts/oop16.ring
call ring scripts/oop17.ring
call ring scripts/oop18.ring
call ring scripts/oop19.ring
call ring scripts/oop20.ring
call ring scripts/oop21.ring
call ring scripts/oop22.ring
call ring scripts/oop23.ring
call ring scripts/oop24.ring
call ring scripts/oop25.ring
call ring scripts/oop26.ring
call ring scripts/oop27.ring
call ring scripts/oop28.ring
call ring scripts/oop29.ring
call ring scripts/oop30.ring
call ring scripts/oop31.ring
call ring scripts/oop32.ring
call ring scripts/oop33.ring
call ring scripts/oop34.ring
call ring scripts/oop35.ring
call ring scripts/oop36.ring
call ring scripts/oop37.ring
call ring scripts/oop38.ring
call ring scripts/oop39.ring
call ring scripts/oop40.ring
call ring scripts/oop41.ring
call ring scripts/oop42.ring
call ring scripts/oop43.ring
call ring scripts/oop44.ring
call ring scripts/oop45.ring
call ring scripts/oop46.ring
call ring scripts/selfbug.ring
call ring scripts/selfininit.ring
call ring scripts/subobjs.ring
call ring scripts/subobjs2.ring
call ring scripts/subobjs3.ring
call ring scripts/subobjs4.ring
call ring scripts/subobjs5.ring
call ring scripts/newinlist.ring
call ring scripts/toop1.ring
call ring scripts/toop2.ring
call ring scripts/toop3.ring
call ring scripts/toop4.ring
call ring scripts/toop5.ring
call ring scripts/toop6.ring
call ring scripts/toop7.ring
call ring scripts/toop8.ring
call ring scripts/toop9.ring
call ring scripts/toop10.ring
call ring scripts/toop11.ring
call ring scripts/string2.ring
call ring scripts/comment.ring
call ring scripts/commenterror.ring
call ring scripts/passbug.ring
call ring scripts/passbug2.ring
call ring scripts/passbug3.ring
call ring scripts/retbug.ring
call ring scripts/privatebug.ring
call ring scripts/privatebug2.ring
call ring scripts/privatebug3.ring
call ring scripts/sort.ring
call ring scripts/sort2.ring
call ring scripts/sort3.ring
call ring scripts/emptyfile.ring
call ring scripts/emptyfile2.ring
call ring scripts/emptyfile3.ring
call ring scripts/emptyfile4.ring
call ring scripts/evaltest.ring
call ring scripts/evalclassbug.ring
call ring scripts/evalmem2.ring
call ring scripts/evalscope.ring
call ring scripts/braceend.ring
call ring scripts/braceend2.ring
call ring scripts/bitwise.ring
call ring scripts/retineval.ring
call ring scripts/retfunc.ring
call ring scripts/math.ring
call ring scripts/newinmethodpara.ring
call ring scripts/newinpara.ring
call ring scripts/findcrash.ring
call ring scripts/initbrace.ring
call ring scripts/callinitmethod.ring
call ring scripts/callinitmethod2.ring
call ring scripts/callinitmethod3.ring
call ring scripts/callmethodfromobj.ring
call ring scripts/braceerror2.ring
call ring scripts/parabracebug.ring
call ring scripts/dotbracebug.ring
call ring scripts/trybug.ring
call ring scripts/forincrash.ring
call ring scripts/forinlist.ring
call ring scripts/timeforfun.ring
call ring scripts/printobj2.ring
call ring scripts/insertfirst.ring
call ring scripts/ppcrash.ring
call ring scripts/ppcrash2.ring
call ring scripts/nestednew3.ring
call ring scripts/each.ring
call ring scripts/retassign.ring
call ring scripts/forinstr.ring
call ring scripts/happynum.ring
call ring scripts/happynum2.ring
call ring scripts/addmethod.ring
call ring scripts/addmethod2.ring
call ring scripts/bracexpreval.ring
call ring scripts/english.ring  < scripts/testenglish.txt
call ring scripts/objectpointer.ring
call ring scripts/double.ring
call ring scripts/funcdef.ring
call ring scripts/funcdef2.ring
call ring scripts/sortlistoneitem.ring
call ring scripts/findlistofobjs.ring
call ring scripts/sortlistofobjsnative.ring
call ring scripts/sortlistofobjsnative2.ring
call ring scripts/substrchar.ring
call ring scripts/ringsqlite.ring
call ring scripts/semicolon.ring
call ring scripts/visualvars.ring
call ring scripts/bracestart.ring
call ring scripts/elseif.ring
call ring scripts/testendinif.ring
call ring scripts/useend.ring
call ring scripts/ifother.ring
call ring scripts/switchelse.ring
call ring scripts/conflict1.ring
call ring scripts/conflict2.ring
call ring scripts/conflict3.ring
call ring scripts/conflict4.ring
call ring scripts/privatemethod.ring
call ring scripts/privateattribute.ring
call ring scripts/dynamicattr1.ring
call ring scripts/dynamicattr2.ring
call ring scripts/sortobjscase.ring
call ring scripts/findlistofobjs2.ring
call ring scripts/ifstylebraces.ring
call ring scripts/whilestylebraces.ring
call ring scripts/forstylebraces.ring
call ring scripts/switchstylebraces.ring
call ring scripts/trystylebraces.ring
call ring scripts/stylebraces.ring
call ring scripts/casetest.ring
call ring scripts/deftest.ring
call ring scripts/forstyle3.ring
call ring scripts/forinstyle3.ring
call ring scripts/changekeyword.ring
call ring scripts/syntaxbasic.ring
call ring scripts/naturaland.ring
call ring scripts/syntaxbasic2.ring
call ring scripts/changeoperator.ring
call ring scripts/naturalplus.ring
call ring scripts/changeoperator2.ring
call ring scripts/evalinbrace.ring
call ring scripts/naturalequal.ring
call ring scripts/rangemaxtomin.ring
call ring scripts/naturaleval.ring
call ring scripts/methodbraceerror.ring
call ring scripts/methodbraceerror2.ring
call ring scripts/methodbraceerror3.ring
call ring scripts/methodbraceerror4.ring
cd scripts
call ring usestylebasic.ring
call ring usestylesupernova.ring
cd ..
call ring scripts/isfunctionclass.ring
call ring scripts/handlebraceerror.ring
call ring scripts/handlebraceerror2.ring
call ring scripts/naturalstring.ring
call ring scripts/selfsearch.ring
call ring scripts/selfafterclass.ring
call ring scripts/selfafterclass2.ring
call ring scripts/selfafterclass3.ring
call ring scripts/selfselfconflict1.ring
call ring scripts/selfselfconflict2.ring
call ring scripts/selfselfconflict3.ring
call ring scripts/selfselfconflict4.ring
call ring scripts/selfselfconflict5.ring
call ring scripts/selfselfconflict6.ring
call ring scripts/assigncrash.ring
call ring scripts/assigncrash2.ring
call ring scripts/assigncrash3.ring
call ring scripts/assigncrash4.ring
call ring scripts/assigncrash5.ring
call ring scripts/assigncrash6.ring
call ring scripts/braceescape.ring
call ring scripts/testconflict.ring
call ring scripts/usingthis.ring
call ring scripts/returninclassregion.ring
call ring scripts/initmethod.ring
call ring scripts/dynamicmethods.ring
call ring scripts/accesssetget.ring
call ring scripts/functionsscope.ring
call ring scripts/functionsscope2.ring
call ring scripts/type2.ring
call ring scripts/tryinsideif.ring
call ring scripts/dotcrash.ring
call ring scripts/braceinlist.ring
call ring scripts/syntaxerror2.ring
call ring scripts/t.ring
call ring scripts/initsyntaxerror.ring
call ring scripts/initinnewbug2.ring
call ring scripts/returnscope.ring
call ring scripts/returnlistfrommethod.ring
call ring scripts/evalbrace.ring
call ring scripts/equalobjobj.ring
call ring scripts/nullpointer.ring
call ring scripts/ptrcmp2.ring
call ring scripts/listandstrconversion.ring
call ring scripts/objmethodnobraceerror.ring
call ring scripts/retselfbyref.ring
call ring scripts/passtemplisttoinitmethod.ring 
call ring scripts/importinsideif.ring 
call ring scripts/liststartinbraces.ring
call ring scripts/privateinnew.ring
call ring scripts/numbers2bytes.ring
call ring scripts/trimerror.ring
call ring scripts/anoninhash.ring
call ring scripts/bracenewinheritance.ring
call ring scripts/nestedfunccall.ring
call ring scripts/classbraces.ring
call ring scripts/funcbraces.ring
call ring scripts/classbraces2.ring
call ring scripts/classend.ring
call ring scripts/packageend.ring
call ring scripts/packagebraces.ring
call ring scripts/endfunc.ring
call ring scripts/types.ring
call ring scripts/inclassregion1.ring 
call ring scripts/inclassregion2.ring
call ring scripts/inclassregion3.ring
call ring scripts/underscoreinnumber.ring
call ring scripts/underscoreinnumber2.ring
call ring scripts/fafternumber.ring
call ring scripts/newtrytest.ring
call ring scripts/newtrytest2.ring
call ring scripts/manygetter.ring
call ring scripts/nosettergetterinclassmethods.ring
call ring scripts/privateattributereuse.ring
call ring scripts/listnovar.ring
call ring scripts/checknull.ring
call ring scripts/selfaddcrash.ring
call ring scripts/errorloc.ring
call ring scripts/rangekeyword.ring
call ring scripts/objdecimals.ring
call ring scripts/literror.ring
call ring scripts/noobject.ring
call ring scripts/objcontainslist.ring
call ring scripts/loadpackage.ring
call ring scripts/testfnicr.ring
call ring scripts/testfnicr2.ring
call ring scripts/plusequalfunc.ring
call ring scripts/varptr.ring
call ring scripts/forloopscope.ring
call ring scripts/chars.ring
call ring scripts/ncemain.ring
call ring scripts/filenameinpara.ring
call ring scripts/filepath1.ring
call ring scripts/ringinring.ring
call ring scripts/ignorenewline.ring
call ring scripts/thisinclassregion.ring
call ring scripts/nullattr.ring
call ring scripts/nullptr.ring
call ring scripts/spaceinlist.ring 
call ring scripts/xortest.ring
call ring scripts/nestednew.ring
call ring scripts/ispointer.ring
call ring scripts/testringvmsee.ring
call ring scripts/minusminus.ring
call ring scripts/retinbrace.ring
call ring scripts/opinlitthenop.ring
call ring scripts/commentcaller.ring
call ring scripts/commentfile.ring
call ring scripts/commentfile2.ring
call ring scripts/selfwrongref.ring
call ring scripts/selfwrongref2.ring
call ring scripts/selfwrongref3.ring
call ring scripts/mysetter.ring
call ring scripts/mysetter2.ring
call ring scripts/mysetter3.ring
call ring scripts/mysetter4.ring
call ring scripts/mysetter5.ring