# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 12/05/2017
# Time : 15:45:10

Load "stdlib.ring"
Load "guilib.ring"

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new lcdnumberView { win.show() } 
		exec()
	}
}

class lcdnumberView from WindowsViewParent
	win = new qMainWindow() { 
		move(100,100)
		resize(400,400)
		setWindowTitle("LCD Number")
		setstylesheet("background-color:;") 
		LCDNumber1 = new qlcdnumber(win) {
			move(37,42)
			resize(215,52)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			Display(1543)
			
		}
		LCDNumber2 = new qlcdnumber(win) {
			move(27,148)
			resize(219,44)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			Display(12)
			
		}
		LCDNumber3 = new qlcdnumber(win) {
			move(43,234)
			resize(212,58)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			Display(40)
			
		}
	}

# End of the Generated Source Code File...