aPackageInfo = [
	:name = "The RingLibSDL Package",
	:description = "Our RingLibSDL package using the Ring programming language",
	:folder = "ringlibsdl",
	:developer = "Mahmoud Fayed",
	:email = "msfclipper@yahoo.com",
	:license = "MIT License",
	:version = "1.0.5",
	:ringversion = "1.18",
	:versions = 	[
		[
			:version = "1.0.5",
			:branch = "master"
		]
	],
	:libs = 	[
		[
			:name = "codegen",
			:version = "1.0",
			:providerusername = ""
		]
	],
	:files = 	[
		"main.ring",
		"README.md"
	],
	:ringfolderfiles = 	[
		"extensions/ringsdl/buildvc.bat",
		"extensions/ringsdl/buildgcc.sh",
		"extensions/ringsdl/document.bat",
		"extensions/ringsdl/gencode.bat",
		"extensions/ringsdl/gencode.sh",
		"extensions/ringsdl/gendoc.ring",
		"extensions/ringsdl/libsdl.cf",
		"extensions/ringsdl/libsdl.ring",
		"extensions/ringsdl/ringlibsdlfuncsdoc.txt",
		"extensions/ringsdl/ring_libsdl.c",
		"extensions/ringsdl/ring_libsdl.rh",
		"extensions/ringsdl/sdl.rh",
		"extensions/ringsdl/SDL2_gfx/acinclude/libtool.m4",
		"extensions/ringsdl/SDL2_gfx/acinclude/ltdl.m4",
		"extensions/ringsdl/SDL2_gfx/acinclude/ltoptions.m4",
		"extensions/ringsdl/SDL2_gfx/acinclude/ltsugar.m4",
		"extensions/ringsdl/SDL2_gfx/acinclude/ltversion.m4",
		"extensions/ringsdl/SDL2_gfx/acinclude/lt~obsolete.m4",
		"extensions/ringsdl/SDL2_gfx/acinclude/pkg.m4",
		"extensions/ringsdl/SDL2_gfx/acinclude/sdl2.m4",
		"extensions/ringsdl/SDL2_gfx/aclocal.m4",
		"extensions/ringsdl/SDL2_gfx/AUTHORS",
		"extensions/ringsdl/SDL2_gfx/autogen.sh",
		"extensions/ringsdl/SDL2_gfx/ChangeLog",
		"extensions/ringsdl/SDL2_gfx/config.guess",
		"extensions/ringsdl/SDL2_gfx/config.sub",
		"extensions/ringsdl/SDL2_gfx/configure",
		"extensions/ringsdl/SDL2_gfx/configure.in",
		"extensions/ringsdl/SDL2_gfx/COPYING",
		"extensions/ringsdl/SDL2_gfx/depcomp",
		"extensions/ringsdl/SDL2_gfx/Docs/html/annotated.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/bc_s.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/bdwn.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/classes.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/closed.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/doxygen.css",
		"extensions/ringsdl/SDL2_gfx/Docs/html/doxygen.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/files.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/functions.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/functions_vars.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x61.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x62.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x63.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x65.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x66.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x67.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x68.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x6c.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x6d.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x70.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x72.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x73.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x74.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x76.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_0x7a.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_defs.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x61.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x62.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x63.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x65.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x66.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x67.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x68.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x6c.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x70.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x72.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x73.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x74.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x76.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_func_0x7a.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/globals_type.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/index.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/jquery.js",
		"extensions/ringsdl/SDL2_gfx/Docs/html/nav_f.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/nav_h.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/open.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/structt_color_r_g_b_a.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/structt_color_y.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/struct_f_p_smanager.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/struct_s_d_l2__gfx_bresenham_iterator.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/struct_s_d_l2__gfx_murphy_iterator.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/tabs.css",
		"extensions/ringsdl/SDL2_gfx/Docs/html/tab_a.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/tab_b.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/tab_h.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/tab_s.png",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_r_e_a_d_m_e.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_r_e_a_d_m_e_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__framerate_8c.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__framerate_8c_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__framerate_8h.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__framerate_8h_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__gfx_primitives_8c.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__gfx_primitives_8c_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__gfx_primitives_8h.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__gfx_primitives_8h_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__gfx_primitives__font_8h.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__gfx_primitives__font_8h_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__image_filter_8c.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__image_filter_8c_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__image_filter_8h.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__image_filter_8h_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__rotozoom_8c.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__rotozoom_8c_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__rotozoom_8h.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html/_s_d_l2__rotozoom_8h_source.html",
		"extensions/ringsdl/SDL2_gfx/Docs/html.doxyfile",
		"extensions/ringsdl/SDL2_gfx/INSTALL",
		"extensions/ringsdl/SDL2_gfx/install-sh",
		"extensions/ringsdl/SDL2_gfx/ltmain.sh",
		"extensions/ringsdl/SDL2_gfx/Makefile.am",
		"extensions/ringsdl/SDL2_gfx/Makefile.in",
		"extensions/ringsdl/SDL2_gfx/missing",
		"extensions/ringsdl/SDL2_gfx/NEWS",
		"extensions/ringsdl/SDL2_gfx/README",
		"extensions/ringsdl/SDL2_gfx/SDL2_framerate.c",
		"extensions/ringsdl/SDL2_gfx/SDL2_framerate.h",
		"extensions/ringsdl/SDL2_gfx/SDL2_gfx.pc.in",
		"extensions/ringsdl/SDL2_gfx/SDL2_gfxPrimitives.c",
		"extensions/ringsdl/SDL2_gfx/SDL2_gfxPrimitives.h",
		"extensions/ringsdl/SDL2_gfx/SDL2_gfxPrimitives_font.h",
		"extensions/ringsdl/SDL2_gfx/SDL2_imageFilter.c",
		"extensions/ringsdl/SDL2_gfx/SDL2_imageFilter.h",
		"extensions/ringsdl/SDL2_gfx/SDL2_rotozoom.c",
		"extensions/ringsdl/SDL2_gfx/SDL2_rotozoom.h",
		"extensions/ringsdl/SDL2_gfx/test/acinclude.m4",
		"extensions/ringsdl/SDL2_gfx/test/aclocal.m4",
		"extensions/ringsdl/SDL2_gfx/test/autogen.sh",
		"extensions/ringsdl/SDL2_gfx/test/config.guess",
		"extensions/ringsdl/SDL2_gfx/test/config.sub",
		"extensions/ringsdl/SDL2_gfx/test/configure",
		"extensions/ringsdl/SDL2_gfx/test/configure.in",
		"extensions/ringsdl/SDL2_gfx/test/install-sh",
		"extensions/ringsdl/SDL2_gfx/test/Makefile.in",
		"extensions/ringsdl/SDL2_gfx/test/README",
		"extensions/ringsdl/SDL2_gfx/test/sample16x16.bmp",
		"extensions/ringsdl/SDL2_gfx/test/sample24-box.bmp",
		"extensions/ringsdl/SDL2_gfx/test/sample24.bmp",
		"extensions/ringsdl/SDL2_gfx/test/sample2x2.bmp",
		"extensions/ringsdl/SDL2_gfx/test/sample3x3.bmp",
		"extensions/ringsdl/SDL2_gfx/test/sample8-box.bmp",
		"extensions/ringsdl/SDL2_gfx/test/sample8.bmp",
		"extensions/ringsdl/SDL2_gfx/test/testgfx.c",
		"extensions/ringsdl/SDL2_gfx/test/TestGfx.vcxproj",
		"extensions/ringsdl/SDL2_gfx/test/testimagefilter.c",
		"extensions/ringsdl/SDL2_gfx/test/TestImageFilter.vcxproj",
		"extensions/ringsdl/SDL2_gfx/test/testrotozoom.c",
		"extensions/ringsdl/SDL2_gfx/test/TestRotozoom.vcxproj",
		"extensions/ringsdl/SDL2_gfx/Win32/Debug/SDL2_gfx.log",
		"extensions/ringsdl/tests/hello.bmp",
		"extensions/ringsdl/tests/hello2.bmp",
		"extensions/ringsdl/tests/hello3.png",
		"extensions/ringsdl/tests/opengl.ring",
		"extensions/ringsdl/tests/opengl2.ring",
		"extensions/ringsdl/tests/opengl3.ring",
		"extensions/ringsdl/tests/opengl4.ring",
		"extensions/ringsdl/tests/opengl5.ring",
		"extensions/ringsdl/tests/pirulen.ttf",
		"extensions/ringsdl/tests/player.png",
		"extensions/ringsdl/tests/sound.wav",
		"extensions/ringsdl/tests/stars.jpg",
		"extensions/ringsdl/tests/test1.ring",
		"extensions/ringsdl/tests/test10.ring",
		"extensions/ringsdl/tests/test2.ring",
		"extensions/ringsdl/tests/test3.ring",
		"extensions/ringsdl/tests/test4.ring",
		"extensions/ringsdl/tests/test5.ring",
		"extensions/ringsdl/tests/test6.ring",
		"extensions/ringsdl/tests/test7.ring",
		"extensions/ringsdl/tests/test8.ring",
		"extensions/ringsdl/tests/test9.ring"
	],
	:windowsfiles = 	[

	],
	:linuxfiles = 	[

	],
	:macosfiles = 	[

	],
	:windowsringfolderfiles = 	[
		"bin/libFLAC-8.dll",
		"bin/libfreetype-6.dll",
		"bin/libjpeg-9.dll",
		"bin/libmodplug-1.dll",
		"bin/libmpg123-0.dll",
		"bin/libogg-0.dll",
		"bin/libpng16-16.dll",
		"bin/load/libsdl.ring",
		"bin/libtiff-5.dll",
		"bin/libvorbis-0.dll",
		"bin/libvorbisfile-3.dll",
		"bin/libwebp-7.dll",
		"bin/ring_sdl.dll",
		"bin/SDL2.dll",
		"bin/SDL2_image.dll",
		"bin/SDL2_mixer.dll",
		"bin/SDL2_net.dll",
		"bin/SDL2_ttf.dll",
		"bin/zlib1.dll"
	],
	:linuxringfolderfiles = 	[

	],
	:macosringfolderfiles = 	[

	],
	:run = "ring main.ring",
	:setup = "",
	:windowssetup = "",
	:linuxsetup = "",
	:macossetup = "",
	:ubuntusetup = "",
	:fedorasetup = "",
	:remotefolder = "ringlibsdl",
	:branch = "master",
	:providerusername = "ringpackages",
	:providerwebsite = "github.com"
]