# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.11 Form Designer
# Date : 17/09/2019
# Time : 20:31:25

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new texteditView { win.show() } 
		exec()
	}
}

class texteditView from WindowsViewParent
	win = new MainWindow() { 
		move(100,100)
		resize(400,400)
		setWindowTitle("Text Edit")
		setstylesheet("background-color:;") 
		TextEdit1 = new textedit(win) {
			move(21,23)
			resize(354,317)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
	}

# End of the Generated Source Code File...