aPackageInfo = [
	:name = "The RingSrc Package",
	:description = "Our RingSrc package using the Ring programming language",
	:folder = "ringsrc",
	:developer = "Mahmoud Fayed",
	:email = "msfclipper@yahoo.com",
	:license = "MIT License",
	:version = "1.10.0",
	:ringversion = "1.10",
	:versions = 	[
		[
			:version = "1.10.0",
			:branch = "master"
		]
	],
	:libs = 	[
		[
			:name = "",
			:version = "",
			:providerusername = ""
		]
	],
	:files = 	[
		"main.ring",
		"README.md"
	],
	:ringfolderfiles = 	[
		"include/ring.h",
		"include/ring_api.h",
		"include/ring_codegen.h",
		"include/ring_ext.h",
		"include/ring_hashlib.h",
		"include/ring_hashtable.h",
		"include/ring_item.h",
		"include/ring_items.h",
		"include/ring_list.h",
		"include/ring_objfile.h",
		"include/ring_parser.h",
		"include/ring_pooldata.h",
		"include/ring_scanner.h",
		"include/ring_state.h",
		"include/ring_string.h",
		"include/ring_vm.h",
		"include/ring_vmdll.h",
		"include/ring_vmfile.h",
		"include/ring_vmgc.h",
		"include/ring_vmgcdata.h",
		"include/ring_vmlistfuncs.h",
		"include/ring_vmmath.h",
		"include/ring_vmos.h",
		"include/ring_vmrefmeta.h",
		"src/buildbccstatic.bat",
		"src/buildclang.sh",
		"src/buildclangstatic.sh",
		"src/buildgcc.sh",
		"src/buildgccstatic.bat",
		"src/buildgccstatic.sh",
		"src/buildtccstatic.bat",
		"src/buildvc.bat",
		"src/buildvcstatic.bat",
		"src/buildvcw.bat",
		"src/installdep.sh",
		"src/installdepfedora.sh",
		"src/installdepmac.sh",
		"src/locatevc.bat",
		"src/ring.c",
		"src/ringw.c",
		"src/ring_api.c",
		"src/ring_codegen.c",
		"src/ring_expr.c",
		"src/ring_ext.c",
		"src/ring_hashlib.c",
		"src/ring_hashtable.c",
		"src/ring_item.c",
		"src/ring_items.c",
		"src/ring_list.c",
		"src/ring_objfile.c",
		"src/ring_parser.c",
		"src/ring_scanner.c",
		"src/ring_state.c",
		"src/ring_stmt.c",
		"src/ring_string.c",
		"src/ring_vm.c",
		"src/ring_vmcui.c",
		"src/ring_vmdll.c",
		"src/ring_vmduprange.c",
		"src/ring_vmexit.c",
		"src/ring_vmexpr.c",
		"src/ring_vmfile.c",
		"src/ring_vmfuncs.c",
		"src/ring_vmgc.c",
		"src/ring_vmjump.c",
		"src/ring_vmlistfuncs.c",
		"src/ring_vmlists.c",
		"src/ring_vmmath.c",
		"src/ring_vmoop.c",
		"src/ring_vmos.c",
		"src/ring_vmperformance.c",
		"src/ring_vmrefmeta.c",
		"src/ring_vmstackvars.c",
		"src/ring_vmstate.c",
		"src/ring_vmstrindex.c",
		"src/ring_vmtrycatch.c",
		"src/ring_vmvars.c"
	],
	:windowsfiles = 	[

	],
	:linuxfiles = 	[

	],
	:macosfiles = 	[

	],
	:run = "ring main.ring",
	:setup = "",
	:remotefolder = "ringsrc",
	:branch = "master",
	:providerusername = "ringpackages",
	:providerwebsite = "github.com"
]