# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 12/05/2017
# Time : 15:27:12

Load "stdlib.ring"
Load "guilib.ring"

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new comboboxView { win.show() } 
		exec()
	}
}

class comboboxView from WindowsViewParent
	win = new qMainWindow() { 
		move(78,87)
		resize(400,400)
		setWindowTitle("Combobox")
		setstylesheet("background-color:;") 
		Combobox1 = new qcombobox(win) {
			move(28,42)
			resize(244,41)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			AddItem("one",0)
			AddItem("two",0)
			AddItem("three",0)
			AddItem("four",0)
			AddItem("five",0)
			setactivatedEvent("")
			setcurrentIndexChangedEvent("")
			seteditTextChangedEvent("")
			sethighlightedEvent("")
			
		}
		Combobox2 = new qcombobox(win) {
			move(26,119)
			resize(217,41)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			AddItem("1",0)
			AddItem("2",0)
			AddItem("3",0)
			AddItem("4",0)
			AddItem("5",0)
			setactivatedEvent("")
			setcurrentIndexChangedEvent("")
			seteditTextChangedEvent("")
			sethighlightedEvent("")
			
		}
	}

# End of the Generated Source Code File...