# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 23:00:39

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new webviewView { win.show() } 
		exec()
	}
}

class webviewView from WindowsViewParent
	win = new qMainWindow() { 
		move(0,85)
		resize(822,400)
		setWindowTitle("WebView")
		setstylesheet("background-color:;") 
		WebView1 = new webview(win) {
			move(13,17)
			resize(793,339)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			loadpage(new qURL("http://www.ring-lang.sf.net"))
			setloadProgressEvent ("")
			setloadStartedEvent ("")
			setselectionChangedEvent ("")
			seturlChangedEvent ("")
			
		}
	}

# End of the Generated Source Code File...