# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 22:59:24

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new treewidgetView { win.show() } 
		exec()
	}
}

class treewidgetView from WindowsViewParent
	win = new qMainWindow() { 
		move(38,70)
		resize(400,400)
		setWindowTitle("TreeWidget")
		setstylesheet("background-color:;") 
		TreeWidget1 = new treewidget(win) {
			move(27,53)
			resize(338,259)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setColumnCount(0)
			setHeaderHidden(True)
			setcollapsedEvent("")
			setexpandedEvent("")
			setactivatedEvent("")
			setclickedEvent("")
			setdoubleClickedEvent("")
			setenteredEvent("")
			setpressedEvent("")
			setviewportEnteredEvent("")
			setcurrentItemChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemCollapsedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemExpandedEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
	}

# End of the Generated Source Code File...