cls

clang -c ring_general.c ring_state.c ring_ext.c ring_hashlib.c ring_hashtable.c ring_vmgc.c ring_os_extension.c ring_string.c ring_list.c ring_item.c ring_items.c ring_scanner.c ring_parser.c ring_stmt.c ring_expr.c ring_codegen.c ring_vm.c ring_vmexpr.c ring_vmvars.c ring_vmlists.c ring_vmfuncs.c ring_api.c ring_vmoop.c ring_vmcui.c ring_vmtrycatch.c ring_vmstrindex.c ring_vmjump.c ring_vmduprange.c ring_vmlistfuncs.c ring_refmeta_extension.c ring_vmperformance.c ring_vmexit.c ring_vmstackvars.c ring_vmstate.c ring_vmgenerallib.c ring_math_extension.c ring_vmfile.c ring_vmdll.c ring_objfile.c -I ..\include 

clang -shared -o ..\..\lib\ring.dll ring_general.o ring_state.o ring_ext.o ring_hashlib.o ring_hashtable.o ring_vmgc.o ring_os_extension.o ring_string.o ring_list.o ring_item.o ring_items.o ring_scanner.o ring_parser.o ring_stmt.o ring_expr.o ring_codegen.o ring_vm.o ring_vmexpr.o ring_vmvars.o ring_vmlists.o ring_vmfuncs.o ring_api.o ring_vmoop.o ring_vmcui.o ring_vmtrycatch.o ring_vmstrindex.o ring_vmjump.o ring_vmduprange.o ring_vmlistfuncs.o ring_refmeta_extension.o ring_vmperformance.o ring_vmexit.o ring_vmstackvars.o ring_vmstate.o ring_vmgenerallib.o ring_math_extension.o ring_vmfile.o ring_vmdll.o ring_objfile.o

ar rcs ..\..\lib\libringstatic.lib ring_general.o ring_state.o ring_ext.o ring_hashlib.o ring_hashtable.o ring_vmgc.o ring_os_extension.o ring_string.o ring_list.o ring_item.o ring_items.o ring_scanner.o ring_parser.o ring_stmt.o ring_expr.o ring_codegen.o ring_vm.o ring_vmexpr.o ring_vmvars.o ring_vmlists.o ring_vmfuncs.o ring_api.o ring_vmoop.o ring_vmcui.o ring_vmtrycatch.o ring_vmstrindex.o ring_vmjump.o ring_vmduprange.o ring_vmlistfuncs.o ring_refmeta_extension.o ring_vmperformance.o ring_vmexit.o ring_vmstackvars.o ring_vmstate.o ring_vmgenerallib.o ring_math_extension.o ring_vmfile.o ring_vmdll.o  ring_objfile.o

clang ring.c ..\..\lib\ring.lib -o ..\..\bin\ring.exe -L ..\..\lib  -I ..\include 

copy ..\..\lib\ring.dll ..\..\bin\ring.dll