aPackageInfo = [
	:name = "The RingWinCReg Package",
	:description = "Our RingWinCReg package using the Ring programming language",
	:folder = "ringwincreg",
	:developer = "msfclipper@yahoo.com",
	:email = "msfclipper@yahoo.com",
	:license = "MIT License",
	:version = "1.0.6",
	:ringversion = "1.20",
	:versions = 	[
		[
			:version = "1.0.6",
			:branch = "master"
		]
	],
	:libs = 	[
		[
			:name = "",
			:version = "",
			:providerusername = ""
		]
	],
	:files = 	[
		"main.ring",
		"README.md"
	],
	:ringfolderfiles = 	[
		"bin/load/wincreg.ring",
		"bin/ring_Wincreg.dll",
		"extensions/ringwincreg/bin/ring_wincreg.dll",
		"extensions/ringwincreg/bin/wincreg.rh",
		"extensions/ringwincreg/bin/wincreg.ring",
		"extensions/ringwincreg/buildvc.bat",
		"extensions/ringwincreg/buildvc_x64.bat",
		"extensions/ringwincreg/creg_regentry.h",
		"extensions/ringwincreg/creg_registry.cpp",
		"extensions/ringwincreg/creg_registry.h",
		"extensions/ringwincreg/docs/bizstyle.js_t",
		"extensions/ringwincreg/docs/build/doctrees/entries.doctree",
		"extensions/ringwincreg/docs/build/doctrees/environment.pickle",
		"extensions/ringwincreg/docs/build/doctrees/extensionfunctions.doctree",
		"extensions/ringwincreg/docs/build/doctrees/implementation&usage.doctree",
		"extensions/ringwincreg/docs/build/doctrees/index.doctree",
		"extensions/ringwincreg/docs/build/doctrees/introduction.doctree",
		"extensions/ringwincreg/docs/build/doctrees/keys.doctree",
		"extensions/ringwincreg/docs/build/doctrees/values.doctree",
		"extensions/ringwincreg/docs/build/html/.buildinfo",
		"extensions/ringwincreg/docs/build/html/entries.html",
		"extensions/ringwincreg/docs/build/html/extensionfunctions.html",
		"extensions/ringwincreg/docs/build/html/genindex.html",
		"extensions/ringwincreg/docs/build/html/implementation&usage.html",
		"extensions/ringwincreg/docs/build/html/index.html",
		"extensions/ringwincreg/docs/build/html/introduction.html",
		"extensions/ringwincreg/docs/build/html/keys.html",
		"extensions/ringwincreg/docs/build/html/logo.png",
		"extensions/ringwincreg/docs/build/html/objects.inv",
		"extensions/ringwincreg/docs/build/html/search.html",
		"extensions/ringwincreg/docs/build/html/searchindex.js",
		"extensions/ringwincreg/docs/build/html/values.html",
		"extensions/ringwincreg/docs/build/html/_sources/entries.txt",
		"extensions/ringwincreg/docs/build/html/_sources/extensionfunctions.txt",
		"extensions/ringwincreg/docs/build/html/_sources/implementation&usage.txt",
		"extensions/ringwincreg/docs/build/html/_sources/index.txt",
		"extensions/ringwincreg/docs/build/html/_sources/introduction.txt",
		"extensions/ringwincreg/docs/build/html/_sources/keys.txt",
		"extensions/ringwincreg/docs/build/html/_sources/values.txt",
		"extensions/ringwincreg/docs/build/html/_static/ajax-loader.gif",
		"extensions/ringwincreg/docs/build/html/_static/background_b01.png",
		"extensions/ringwincreg/docs/build/html/_static/basic.css",
		"extensions/ringwincreg/docs/build/html/_static/bizstyle.css",
		"extensions/ringwincreg/docs/build/html/_static/bizstyle.js",
		"extensions/ringwincreg/docs/build/html/_static/bizstyle.js_t.bak",
		"extensions/ringwincreg/docs/build/html/_static/bizstyle.js_t.bak.old",
		"extensions/ringwincreg/docs/build/html/_static/comment-bright.png",
		"extensions/ringwincreg/docs/build/html/_static/comment-close.png",
		"extensions/ringwincreg/docs/build/html/_static/comment.png",
		"extensions/ringwincreg/docs/build/html/_static/css3-mediaqueries.js",
		"extensions/ringwincreg/docs/build/html/_static/css3-mediaqueries_src.js",
		"extensions/ringwincreg/docs/build/html/_static/doctools.js",
		"extensions/ringwincreg/docs/build/html/_static/down-pressed.png",
		"extensions/ringwincreg/docs/build/html/_static/down.png",
		"extensions/ringwincreg/docs/build/html/_static/file.png",
		"extensions/ringwincreg/docs/build/html/_static/jquery-3.1.0.js",
		"extensions/ringwincreg/docs/build/html/_static/jquery.js",
		"extensions/ringwincreg/docs/build/html/_static/minus.png",
		"extensions/ringwincreg/docs/build/html/_static/plus.png",
		"extensions/ringwincreg/docs/build/html/_static/pygments.css",
		"extensions/ringwincreg/docs/build/html/_static/searchtools.js",
		"extensions/ringwincreg/docs/build/html/_static/underscore-1.3.1.js",
		"extensions/ringwincreg/docs/build/html/_static/underscore.js",
		"extensions/ringwincreg/docs/build/html/_static/up-pressed.png",
		"extensions/ringwincreg/docs/build/html/_static/up.png",
		"extensions/ringwincreg/docs/build/html/_static/websupport.js",
		"extensions/ringwincreg/docs/layout.html",
		"extensions/ringwincreg/docs/logo.png",
		"extensions/ringwincreg/docs/make.bat",
		"extensions/ringwincreg/docs/Makefile",
		"extensions/ringwincreg/docs/PrepareStyle.bat",
		"extensions/ringwincreg/docs/README.md",
		"extensions/ringwincreg/docs/source/conf.py",
		"extensions/ringwincreg/docs/source/entries.txt",
		"extensions/ringwincreg/docs/source/extensionfunctions.txt",
		"extensions/ringwincreg/docs/source/implementation&usage.txt",
		"extensions/ringwincreg/docs/source/index.txt",
		"extensions/ringwincreg/docs/source/introduction.txt",
		"extensions/ringwincreg/docs/source/keys.txt",
		"extensions/ringwincreg/docs/source/values.txt",
		"extensions/ringwincreg/Documentation.html",
		"extensions/ringwincreg/LICENSE.md",
		"extensions/ringwincreg/README.md",
		"extensions/ringwincreg/ring_wincreg.cpp",
		"extensions/ringwincreg/ring_wincreg.dll.manifest",
		"extensions/ringwincreg/ring_wincreg.h",
		"tools/ring2exe/libs/wincreg.ring"
	],
	:windowsfiles = 	[

	],
	:linuxfiles = 	[

	],
	:macosfiles = 	[

	],
	:windowsringfolderfiles = 	[

	],
	:linuxringfolderfiles = 	[

	],
	:macosringfolderfiles = 	[

	],
	:run = "ring main.ring",
	:setup = "",
	:windowssetup = "",
	:linuxsetup = "",
	:macossetup = "",
	:ubuntusetup = "",
	:fedorasetup = "",
	:remotefolder = "ringwincreg",
	:branch = "master",
	:providerusername = "ringpackages",
	:providerwebsite = "github.com"
]