aPackageInfo = [
	:name = "The GoldMagic800 Package",
	:description = "Our GoldMagic800 package using the Ring programming language",
	:folder = "goldmagic800",
	:developer = "Mahmoud Fayed",
	:email = "msfclipper@yahoo.com",
	:license = "MIT License",
	:version = "1.0.3",
	:ringversion = "1.19",
	:versions = 	[
		[
			:version = "1.0.3",
			:branch = "master"
		]
	],
	:libs = 	[
		[
			:name = "ringallegro",
			:version = "1.0",
			:providerusername = ""
		],
		[
			:name = "ringopengl21",
			:version = "1.0",
			:providerusername = ""
		]
	],
	:files = 	[
		"main.ring",
		"README.md"
	],
	:ringfolderfiles = 	[
		"applications/goldmagic800/editor/editor.rform",
		"applications/goldmagic800/editor/editorConstants.ring",
		"applications/goldmagic800/editor/editorController.ring",
		"applications/goldmagic800/editor/editorView.ring",
		"applications/goldmagic800/editor/gold.ico",
		"applications/goldmagic800/editor/leveleditor.rc",
		"applications/goldmagic800/editor/leveleditor.ring",
		"applications/goldmagic800/font/arial.ttf",
		"applications/goldmagic800/gamebase.ring",
		"applications/goldmagic800/gamecamera.ring",
		"applications/goldmagic800/gamedata.ring",
		"applications/goldmagic800/gamedraw.ring",
		"applications/goldmagic800/gameengine.ring",
		"applications/goldmagic800/gameerror.ring",
		"applications/goldmagic800/gamefiles.ring",
		"applications/goldmagic800/gamehowtoplay.ring",
		"applications/goldmagic800/gamelevel.ring",
		"applications/goldmagic800/gamelogo.ring",
		"applications/goldmagic800/gamemainmenu.ring",
		"applications/goldmagic800/gamemouse.ring",
		"applications/goldmagic800/gameplayer.ring",
		"applications/goldmagic800/gameresources.ring",
		"applications/goldmagic800/gamescreen.ring",
		"applications/goldmagic800/gameselectlevel.ring",
		"applications/goldmagic800/gamesound.ring",
		"applications/goldmagic800/gamestory.ring",
		"applications/goldmagic800/gold.ico",
		"applications/goldmagic800/goldmagic800.rc",
		"applications/goldmagic800/goldmagic800.ring",
		"applications/goldmagic800/images/gameenv.jpg",
		"applications/goldmagic800/images/gametitle.jpg",
		"applications/goldmagic800/images/gold.jpg",
		"applications/goldmagic800/images/ground1.jpg",
		"applications/goldmagic800/images/ground2.jpg",
		"applications/goldmagic800/images/ground3.jpg",
		"applications/goldmagic800/images/howtoplay.jpg",
		"applications/goldmagic800/images/logo.jpg",
		"applications/goldmagic800/images/mainmenu.jpg",
		"applications/goldmagic800/images/manygold.jpg",
		"applications/goldmagic800/images/n1.jpg",
		"applications/goldmagic800/images/n10.jpg",
		"applications/goldmagic800/images/n11.jpg",
		"applications/goldmagic800/images/n12.jpg",
		"applications/goldmagic800/images/n13.jpg",
		"applications/goldmagic800/images/n14.jpg",
		"applications/goldmagic800/images/n15.jpg",
		"applications/goldmagic800/images/n16.jpg",
		"applications/goldmagic800/images/n2.jpg",
		"applications/goldmagic800/images/n3.jpg",
		"applications/goldmagic800/images/n4.jpg",
		"applications/goldmagic800/images/n5.jpg",
		"applications/goldmagic800/images/n6.jpg",
		"applications/goldmagic800/images/n7.jpg",
		"applications/goldmagic800/images/n8.jpg",
		"applications/goldmagic800/images/n9.jpg",
		"applications/goldmagic800/images/newwall.jpg",
		"applications/goldmagic800/images/oldlogo.jpg",
		"applications/goldmagic800/images/playback.jpg",
		"applications/goldmagic800/images/player.jpg",
		"applications/goldmagic800/images/remotecontrol.jpg",
		"applications/goldmagic800/images/storyback.jpg",
		"applications/goldmagic800/images/storyback2.jpg",
		"applications/goldmagic800/images/storyback3.jpg",
		"applications/goldmagic800/images/thebox.jpg",
		"applications/goldmagic800/images/wall1.jpg",
		"applications/goldmagic800/images/wall2.jpg",
		"applications/goldmagic800/images/wall3.jpg",
		"applications/goldmagic800/images/wall4.jpg",
		"applications/goldmagic800/images/winback.jpg",
		"applications/goldmagic800/levels/level1.level",
		"applications/goldmagic800/levels/level10.level",
		"applications/goldmagic800/levels/level11.level",
		"applications/goldmagic800/levels/level12.level",
		"applications/goldmagic800/levels/level13.level",
		"applications/goldmagic800/levels/level14.level",
		"applications/goldmagic800/levels/level15.level",
		"applications/goldmagic800/levels/level16.level",
		"applications/goldmagic800/levels/level17.level",
		"applications/goldmagic800/levels/level18.level",
		"applications/goldmagic800/levels/level19.level",
		"applications/goldmagic800/levels/level20.level",
		"applications/goldmagic800/levels/level21.level",
		"applications/goldmagic800/levels/level22.level",
		"applications/goldmagic800/levels/level23.level",
		"applications/goldmagic800/levels/level24.level",
		"applications/goldmagic800/levels/level25.level",
		"applications/goldmagic800/levels/level26.level",
		"applications/goldmagic800/levels/level27.level",
		"applications/goldmagic800/levels/level28.level",
		"applications/goldmagic800/levels/level29.level",
		"applications/goldmagic800/levels/level2.level",
		"applications/goldmagic800/levels/level3.level",
		"applications/goldmagic800/levels/level30.level",
		"applications/goldmagic800/levels/level31.level",
		"applications/goldmagic800/levels/level32.level",
		"applications/goldmagic800/levels/level33.level",
		"applications/goldmagic800/levels/level34.level",
		"applications/goldmagic800/levels/level35.level",
		"applications/goldmagic800/levels/level36.level",
		"applications/goldmagic800/levels/level37.level",
		"applications/goldmagic800/levels/level38.level",
		"applications/goldmagic800/levels/level39.level",
		"applications/goldmagic800/levels/level4.level",
		"applications/goldmagic800/levels/level40.level",
		"applications/goldmagic800/levels/level41.level",
		"applications/goldmagic800/levels/level42.level",
		"applications/goldmagic800/levels/level43.level",
		"applications/goldmagic800/levels/level44.level",
		"applications/goldmagic800/levels/level5.level",
		"applications/goldmagic800/levels/level6.level",
		"applications/goldmagic800/levels/level7.level",
		"applications/goldmagic800/levels/level8.level",
		"applications/goldmagic800/levels/level9.level",
		"applications/goldmagic800/README.md",
		"applications/goldmagic800/sound/menuchange.wav",
		"applications/goldmagic800/sound/menuchange2.wav",
		"applications/goldmagic800/sound/menuclick.wav",
		"applications/goldmagic800/sound/menuclick2.wav",
		"applications/goldmagic800/sound/music1.wav",
		"applications/goldmagic800/sound/music2.wav",
		"applications/goldmagic800/sound/music3.wav",
		"applications/goldmagic800/sound/sfx_die.wav",
		"applications/goldmagic800/sound/sfx_hit.wav",
		"applications/goldmagic800/sound/sfx_point.wav",
		"applications/goldmagic800/sound/storymusic.wav"
	],
	:windowsfiles = 	[

	],
	:linuxfiles = 	[

	],
	:macosfiles = 	[

	],
	:windowsringfolderfiles = 	[

	],
	:linuxringfolderfiles = 	[

	],
	:macosringfolderfiles = 	[

	],
	:run = "ring main.ring",
	:setup = "",
	:windowssetup = "",
	:linuxsetup = "",
	:macossetup = "",
	:ubuntusetup = "",
	:fedorasetup = "",
	:remotefolder = "goldmagic800",
	:branch = "master",
	:providerusername = "ringpackages",
	:providerwebsite = "github.com"
]