# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 12/05/2017
# Time : 15:15:15

Load "stdlib.ring"
Load "guilib.ring"

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new sliderView { win.show() } 
		exec()
	}
}

class sliderView from WindowsViewParent
	win = new qMainWindow() { 
		move(36,65)
		resize(400,400)
		setWindowTitle("Slider")
		setstylesheet("background-color:;") 
		Slider1 = new qslider(win) {
			move(46,81)
			resize(300,44)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setOrientation(1)
			setactionTriggeredEvent("")
			setrangeChangedEvent("")
			setsliderMovedEvent("")
			setsliderPressedEvent("")
			setsliderReleasedEvent("")
			setvalueChangedEvent("")
			
		}
		Slider2 = new qslider(win) {
			move(39,142)
			resize(65,154)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setOrientation(0)
			setValue(50)
			setactionTriggeredEvent("")
			setrangeChangedEvent("")
			setsliderMovedEvent("")
			setsliderPressedEvent("")
			setsliderReleasedEvent("")
			setvalueChangedEvent("")
			
		}
	}

# End of the Generated Source Code File...