# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 06/05/2017
# Time : 07:13:48

Load "stdlib.ring"
Load "guilib.ring"

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new sayhelloView { win.show() } 
		exec()
	}
}

class sayhelloView from WindowsViewParent
	win = new qMainWindow() { 
		move(32,77)
		resize(414,204)
		setWindowTitle("Say Hello")
		setstylesheet("background-color:;") 
		Label1 = new qlabel(win) {
			move(9,34)
			resize(107,40)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Enter your name ?")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		LineEdit1 = new qlineedit(win) {
			move(142,35)
			resize(254,40)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Button1 = new qpushbutton(win) {
			move(9,102)
			resize(109,35)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Say Hello")
			setClickEvent(Method(:SayHello))
			setBtnImage(Button1,"")
			
		}
		LineEdit2 = new qlineedit(win) {
			move(142,102)
			resize(254,40)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
	}

# End of the Generated Source Code File...