# The Ring Natural Library
# 2017-2026, Mahmoud Fayed <msfclipper@yahoo.com>

# Disable Keywords

changeringkeyword again 		_again
changeringkeyword and  			_and
changeringkeyword but 			_but
changeringkeyword bye 			_bye
changeringkeyword call 			_call
changeringkeyword case 			_case
changeringkeyword catch 		_catch
changeringkeyword class 		_class
changeringkeyword def 			_def
changeringkeyword do 			_do
changeringkeyword done 			_done
changeringkeyword else 			_else
changeringkeyword elseif 		_elseif
changeringkeyword end 			_end
changeringkeyword exit 			_exit
changeringkeyword for 			_for
changeringkeyword foreach		_foreach
changeringkeyword from 			_from
changeringkeyword func 			_func
changeringkeyword get 			_get
changeringkeyword give 			_give
changeringkeyword if 			_if
changeringkeyword import 		_import
changeringkeyword in 			_in
changeringkeyword load 			_load
changeringkeyword loop 			_loop
changeringkeyword new 			_new
changeringkeyword next 			_next
changeringkeyword not 			_not
changeringkeyword off 			_off
changeringkeyword ok 			_ok
changeringkeyword on 			_on
changeringkeyword or 			_or
changeringkeyword other 		_other
changeringkeyword package 		_package
changeringkeyword private 		_private
changeringkeyword put 			_put
changeringkeyword return 		_return
changeringkeyword see 			_see
changeringkeyword step 			_step
changeringkeyword switch 		_switch
changeringkeyword to 			_to
changeringkeyword try 			_try
changeringkeyword while 		_while
changeringkeyword endfunc 		_endfunc
changeringkeyword endclass 		_endclass
changeringkeyword endpackage	_endpackage
changeringkeyword endif 		_endif
changeringkeyword endfor 		_endfor
changeringkeyword endwhile 		_endwhile
changeringkeyword endswitch 	_endswitch
changeringkeyword endtry 		_endtry
changeringkeyword function 		_function
changeringkeyword endfunction	_endfunction
changeringkeyword break 		_break
changeringkeyword continue 		_continue

# Disable Operators

changeringoperator +			_+
changeringoperator -			_-
changeringoperator *			_*
changeringoperator /			_/
changeringoperator %			_%
changeringoperator =			_=
changeringoperator !			_!
changeringoperator <			_<
changeringoperator >			_>
changeringoperator &			_&
changeringoperator |			_|
changeringoperator ^			_^
changeringoperator ~			_~
changeringoperator :			_:
changeringoperator [			_[
changeringoperator ]			_]
changeringoperator (			_(
changeringoperator )			_)
changeringoperator .			_.
changeringoperator ,			_,

