# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.11 Form Designer
# Date : 17/09/2019
# Time : 20:28:38

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new comboboxView { win.show() } 
		exec()
	}
}

class comboboxView from WindowsViewParent
	win = new MainWindow() { 
		move(78,87)
		resize(400,400)
		setWindowTitle("Combobox")
		setstylesheet("background-color:;") 
		Combobox1 = new combobox(win) {
			move(28,42)
			resize(244,41)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			AddItem("one",0)
			AddItem("two",0)
			AddItem("three",0)
			AddItem("four",0)
			AddItem("five",0)
			setactivatedEvent("")
			setcurrentIndexChangedEvent("")
			seteditTextChangedEvent("")
			sethighlightedEvent("")
			
		}
		Combobox2 = new combobox(win) {
			move(26,119)
			resize(217,41)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			AddItem("1",0)
			AddItem("2",0)
			AddItem("3",0)
			AddItem("4",0)
			AddItem("5",0)
			setactivatedEvent("")
			setcurrentIndexChangedEvent("")
			seteditTextChangedEvent("")
			sethighlightedEvent("")
			
		}
	}

# End of the Generated Source Code File...