# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 22:58:46

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new tablewidgetView { win.show() } 
		exec()
	}
}

class tablewidgetView from WindowsViewParent
	win = new qMainWindow() { 
		move(37,74)
		resize(400,400)
		setWindowTitle("Table Widget")
		setstylesheet("background-color:;") 
		TableWidget1 = new tablewidget(win) {
			move(16,35)
			resize(353,302)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setColumnCount(3)
			setHorizontalHeaderItem(0, new QTableWidgetItem("one"))
			setHorizontalHeaderItem(1, new QTableWidgetItem("two"))
			setHorizontalHeaderItem(2, new QTableWidgetItem("three"))
			setSelectionBehavior(QAbstractItemView_SelectItems)
			setAlternatingRowColors(True)
			setcellActivatedEvent("")
			setcellChangedEvent("")
			setcellClickedEvent("")
			setcellDoubleClickedEvent("")
			setcellEnteredEvent("")
			setcellPressedEvent("")
			setcurrentCellChangedEvent("")
			setcurrentItemChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
	}

# End of the Generated Source Code File...