# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.11 Form Designer
# Date : 17/09/2019
# Time : 20:30:02

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new menubarView { win.show() } 
		exec()
	}
}

class menubarView from WindowsViewParent
	win = new MainWindow() { 
		move(24,89)
		resize(400,400)
		setWindowTitle("Using the Menubar")
		setstylesheet("background-color:;") 

		setWindowFlags(Qt_Window | Qt_WindowCloseButtonHint | Qt_WindowStaysOnTopHint | Qt_CustomizeWindowHint) 

		oMenuBar = new qmenubar(win) {
			subMenu1 = addmenu("File")
			subMenu1 {

				oAction1_1 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("New")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction1_1)

				oAction1_2 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Open")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction1_2)

				oAction1_3 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Save")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction1_3)

				oAction1_4 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Save As")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction1_4)

				oAction1_5 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Close")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction1_5)

				oAction1_6 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Exit")
					setclickevent(Method(:closewindow))
				}
				addaction(oAction1_6)
			}
			subMenu2 = addmenu("Edit")
			subMenu2 {

				oAction2_1 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Cut")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction2_1)

				oAction2_2 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Copy")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction2_2)

				oAction2_3 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Paste")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction2_3)
			}
			subMenu3 = addmenu("Help")
			subMenu3 {
			subMenu4 = addmenu("HTML")
			subMenu4 {

				oAction4_1 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("PDF")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction4_1)

				oAction4_2 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("CHM")
					setclickevent(Method(:NoAction))
				}
				addaction(oAction4_2)
			}
			}
		}
		win.SetMenuBar(oMenuBar)
 
	}

# End of the Generated Source Code File...