# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 23:00:15

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new videowidgetView { win.show() } 
		exec()
	}
}

class videowidgetView from WindowsViewParent
	win = new qMainWindow() { 
		move(63,87)
		resize(400,400)
		setWindowTitle("Video Widget")
		setstylesheet("background-color:;") 
		VideoWidget1 = new videowidget(win) {
			move(12,38)
			resize(371,305)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			playerVideoWidget1 = new qmediaplayer() { 
			setmedia(new qurl("test.avi"))
			 setvideooutput(VideoWidget1)
			}
			
		}
		Button1 = new pushbutton(win) {
			move(14,5)
			resize(100,29)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Play")
			setClickEvent(Method(:PlayVideo))
			setBtnImage(Button1,"")
			
		}
	}

# End of the Generated Source Code File...