#-------------------------------------------------------------------------#
load "core/qobject.ring"
load "core/qiodevice.ring"
load "core/qprocess.ring"
load "core/qthread.ring"
#-------------------------------------------------------------------------#
load "gui/qwindow.ring"
load "gui/qguiapplication.ring"
load "gui/qdrag.ring"
load "gui/qmovie.ring"
#-------------------------------------------------------------------------#
load "widgets/qpushbutton.ring"
load "widgets/qaction.ring"
load "widgets/qlineedit.ring"
load "widgets/qtextedit.ring"
load "widgets/qlistwidget.ring"
load "widgets/qtreeview.ring"
load "widgets/qtreewidget.ring"
load "widgets/qcombobox.ring"
load "widgets/qtabwidget.ring"
load "widgets/qtablewidget.ring"
load "widgets/qprogressbar.ring"
load "widgets/qspinbox.ring"
load "widgets/qslider.ring"
load "widgets/qdial.ring"
load "widgets/qcheckbox.ring"
load "widgets/qradiobutton.ring"
load "widgets/qbuttongroup.ring"
load "widgets/qtimer.ring"
load "widgets/qplaintextedit.ring"
load "widgets/qheaderview.ring"
load "widgets/qtoolbutton.ring"
load "widgets/qtextbrowser.ring"
load "widgets/qdockwidget.ring"
load "widgets/qstackedwidget.ring"
load "widgets/qcalenderwidget.ring"
load "widgets/qtabbar.ring"
load "widgets/qfiledialog.ring"
load "widgets/qcolordialog.ring"
load "widgets/qfontdialog.ring"
#-------------------------------------------------------------------------#
load "printsupport/qprintpreviewwidget.ring"
load "printsupport/qprintpreviewdialog.ring"
load "printsupport/qprintdialog.ring"
#-------------------------------------------------------------------------#
load "network/qabstractsocket.ring"
load "network/qnetworkaccessmanager.ring"
load "network/qtcpserver.ring"
#-------------------------------------------------------------------------#
load "multimediawidgets/qvideowidget.ring"
#-------------------------------------------------------------------------#
load "quick/qquickwidget.ring"
#-------------------------------------------------------------------------#
load "positioning/qgeopositioninfosource.ring"
#-------------------------------------------------------------------------#
load "serialport/qserialport.ring"
#-------------------------------------------------------------------------#
load "web/qwebview.ring"
load "web/qwebengineview.ring"
load "web/qwebenginepage.ring"
#-------------------------------------------------------------------------#
load "speech/qtexttospeech.ring"
#-------------------------------------------------------------------------#
load "qt3d/qobjectpicker.ring"
load "qt3d/qframeaction.ring"
#-------------------------------------------------------------------------#
load "bluetooth/qbluetoothdevicediscoveryagent.ring"
load "bluetooth/qbluetoothlocaldevice.ring"
load "bluetooth/qbluetoothserver.ring"
load "bluetooth/qbluetoothservicediscoveryagent.ring"
load "bluetooth/qbluetoothsocket.ring"
load "bluetooth/qbluetoothtransfermanager.ring"
load "bluetooth/qbluetoothtransferreply.ring"
#-------------------------------------------------------------------------#
load "charts/qabstractaxis.ring"
load "charts/qabstractbarseries.ring"
load "charts/qabstractseries.ring"
load "charts/qareaseries.ring"
load "charts/qbarcategoryaxis.ring"
load "charts/qbarset.ring"
load "charts/qboxplotseries.ring"
load "charts/qboxset.ring"
load "charts/qcandlestickmodelmapper.ring"
load "charts/qcandlestickseries.ring"
load "charts/qcandlestickset.ring"
load "charts/qcategoryaxis.ring"
load "charts/qchart.ring"
load "charts/qdatetimeaxis.ring"
load "charts/qhbarmodelmapper.ring"
load "charts/qhboxplotmodelmapper.ring"
load "charts/qhcandlestickmodelmapper.ring"
load "charts/qhpiemodelmapper.ring"
load "charts/qhxymodelmapper.ring"
load "charts/qlegendmarker.ring"
load "charts/qlogvalueaxis.ring"
load "charts/qpieseries.ring"
load "charts/qpieslice.ring"
load "charts/qscatterseries.ring"
load "charts/qvbarmodelmapper.ring"
load "charts/qvboxplotmodelmapper.ring"
load "charts/qvcandlestickmodelmapper.ring"
load "charts/qvpiemodelmapper.ring"
load "charts/qvxymodelmapper.ring"
load "charts/qvalueaxis.ring"
load "charts/qxyseries.ring"
#-------------------------------------------------------------------------#
load "graphicsview/qgraphicsscene.ring"
load "graphicsview/qgraphicseffect.ring"
load "graphicsview/qgraphicsobject.ring"
load "graphicsview/qgraphicstextitem.ring"
