<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ring</string>
	</array>
	<key>name</key>
	<string>ring</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string3</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numericConstant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#controlKeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#classDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functionDefinition</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(len|reverse|add|del|get|clock|lower|upper|input|asci|char|date|time)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(filename|getchar|system|isstring|isnumber|islist|type|isnull|read|write)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(hex|dec|number|string|str2hex|hex2str|left|write|trim|copy|substr|eval)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(raise|assert|ismethod)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(sin|cos|tan|asin|acos|atan|atan2|sinh|cosh|tanh|exp|log|log10)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(ceil|floor|fabs|pow|sqrt)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(fopen|fclose|fflush|freopen|tempfile|tempname|fseek|ftell)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(rewind|fgetpos|fsetpos|clearerr|feof|ferror|perror|rename|remove)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(fgetc|fgets|fputc|fputs|ungetc|fread|fwrite)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(odbc_init|odbc_drivers|odbc_datasources|odbc_close|odbc_connect|odbc_disconnect)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(odbc_execute|odbc_colcount|odbc_fetch|odbc_getdata|odbc_tables)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(odbc_columns|odbc_autocommit|odbc_commit|odbc_rollback|odbc_rowcount)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(mysql_info|mysql_init|mysql_error|mysql_connect|mysql_close)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(mysql_query|mysql_result|mysql_insert_id|mysql_columns|mysql_result2)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>(?i:\b(mysql_next_result|mysql_escapse_string|mysql_autocommit|mysql_commit|mysql_rollback)\b)</string>
			<key>name</key>
			<string>keyword.ring</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>classDefinition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.vbnet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.vbnet</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:\b(class|package)\s+([a-zA-Z_]\w*)\s*)</string>
			<key>name</key>
			<string>meta.class.ring</string>
		</dict>
		<key>comment1</key>
		<dict>
			<key>match</key>
			<string>(#.*)</string>
			<key>name</key>
			<string>comment.ring</string>
		</dict>
		<key>comment2</key>
		<dict>
			<key>match</key>
			<string>(^\s*\*.*)</string>
			<key>name</key>
			<string>comment.ring</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>(?i:(\.t\.|\.f\.|\.null\.))</string>
			<key>name</key>
			<string>constant.ring</string>
		</dict>
		<key>controlKeywords</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(see|nl|stdin|stdout|bye|true|false|and|or|not|if|but|else|ok|switch|on|off|while|end|for|next|to|in|do|again|return|load|import|new|try|catch|done|endif|endfor|endwhile|endswitch|endtry|break|continue|function|endfunction)\b)</string>
			<key>name</key>
			<string>keyword.control.ring</string>
		</dict>
		<key>functionDefinition</key>
		<dict>
			<key>begin</key>
			<string>(?i:\b(proc[e]?[d]?[u]?[r]?[e]?|func[t]?[i]?[o]?[n]?)\s+([a-zA-Z_]\w*)\s*(\()?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.function.vbnet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.vbnet</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.parameters.vbnet</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.vbnet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))?\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.vbnet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.vbnet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#otherKeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#supportTypes</string>
				</dict>
			</array>
		</dict>
		<key>numericConstant</key>
		<dict>
			<key>match</key>
			<string>\b(-?\d+(\.?\d?)*)</string>
			<key>name</key>
			<string>constant.ring</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>\b(\+|\-|\^|\*|\=)\b</string>
			<key>name</key>
			<string>keyword.operator.ring</string>
		</dict>
		<key>string1</key>
		<dict>
			<key>match</key>
			<string>(")(.*)(")</string>
			<key>name</key>
			<string>string.ring</string>
		</dict>
		<key>string2</key>
		<dict>
			<key>match</key>
			<string>(')(.*)(')</string>
			<key>name</key>
			<string>string.ring</string>
		</dict>
		<key>string3</key>
		<dict>
			<key>match</key>
			<string>(\[)(.*)(\])</string>
			<key>name</key>
			<string>string.ring</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>.ring</string>
	<key>uuid</key>
	<string>720071d7-bf91-4540-a12a-b611f9c41729</string>
</dict>
</plist>
