aPackageInfo = [
	:name = "The extensionstutorials Package",
	:description = "Our extensionstutorials package using the Ring programming language",
	:folder = "extensionstutorials",
	:developer = "Mahmoud Fayed",
	:email = "msfclipper@yahoo.com",
	:license = "MIT License",
	:version = "1.0.1",
	:ringversion = "1.20",
	:versions = 	[
		[
			:version = "1.0.1",
			:branch = "master"
		]
	],
	:libs = 	[
		[
			:name = "",
			:version = "",
			:providerusername = ""
		]
	],
	:files = 	[
		"main.ring"
	],
	:ringfolderfiles = 	[
		"extensions/tutorial/createtable/buildclang.sh",
		"extensions/tutorial/createtable/buildgcc.sh",
		"extensions/tutorial/createtable/buildvc.bat",
		"extensions/tutorial/createtable/buildvc_x64.bat",
		"extensions/tutorial/createtable/mylib.c",
		"extensions/tutorial/createtable/mylib.ring",
		"extensions/tutorial/createtable/README.md",
		"extensions/tutorial/createtable/test.ring",
		"extensions/tutorial/displaylist/buildclang.sh",
		"extensions/tutorial/displaylist/buildgcc.sh",
		"extensions/tutorial/displaylist/buildvc.bat",
		"extensions/tutorial/displaylist/buildvc_x64.bat",
		"extensions/tutorial/displaylist/mylib.c",
		"extensions/tutorial/displaylist/mylib.ring",
		"extensions/tutorial/displaylist/README.md",
		"extensions/tutorial/displaylist/test.ring",
		"extensions/tutorial/filterlist/buildclang.sh",
		"extensions/tutorial/filterlist/buildgcc.sh",
		"extensions/tutorial/filterlist/buildvc.bat",
		"extensions/tutorial/filterlist/buildvc_x64.bat",
		"extensions/tutorial/filterlist/mylib.c",
		"extensions/tutorial/filterlist/mylib.ring",
		"extensions/tutorial/filterlist/README.md",
		"extensions/tutorial/filterlist/test.ring",
		"extensions/tutorial/generatelist/buildclang.sh",
		"extensions/tutorial/generatelist/buildgcc.sh",
		"extensions/tutorial/generatelist/buildvc.bat",
		"extensions/tutorial/generatelist/buildvc_x64.bat",
		"extensions/tutorial/generatelist/mylib.c",
		"extensions/tutorial/generatelist/mylib.ring",
		"extensions/tutorial/generatelist/README.md",
		"extensions/tutorial/generatelist/test.ring",
		"extensions/tutorial/helloworld/buildvc.bat",
		"extensions/tutorial/helloworld/buildvc_x64.bat",
		"extensions/tutorial/helloworld/mylib.c",
		"extensions/tutorial/helloworld/README.md",
		"extensions/tutorial/helloworld/test.ring",
		"extensions/tutorial/helloworld2/buildclang.sh",
		"extensions/tutorial/helloworld2/buildgcc.sh",
		"extensions/tutorial/helloworld2/buildvc.bat",
		"extensions/tutorial/helloworld2/buildvc_x64.bat",
		"extensions/tutorial/helloworld2/mylib.c",
		"extensions/tutorial/helloworld2/mylib.ring",
		"extensions/tutorial/helloworld2/README.md",
		"extensions/tutorial/helloworld2/test.ring",
		"extensions/tutorial/incrementlist/buildclang.sh",
		"extensions/tutorial/incrementlist/buildgcc.sh",
		"extensions/tutorial/incrementlist/buildvc.bat",
		"extensions/tutorial/incrementlist/buildvc_x64.bat",
		"extensions/tutorial/incrementlist/mylib.c",
		"extensions/tutorial/incrementlist/mylib.ring",
		"extensions/tutorial/incrementlist/README.md",
		"extensions/tutorial/incrementlist/test.ring",
		"extensions/tutorial/integerpointer/buildvc.bat",
		"extensions/tutorial/integerpointer/buildvc_x64.bat",
		"extensions/tutorial/integerpointer/mylib.c",
		"extensions/tutorial/integerpointer/README.md",
		"extensions/tutorial/integerpointer/test.ring",
		"extensions/tutorial/mandelbrot/buildvc.bat",
		"extensions/tutorial/mandelbrot/buildvc_x64.bat",
		"extensions/tutorial/mandelbrot/Mandelbrot.ring",
		"extensions/tutorial/mandelbrot/mylib.c",
		"extensions/tutorial/mandelbrot/mylib.ring",
		"extensions/tutorial/mandelbrot/README.md",
		"extensions/tutorial/README.md",
		"extensions/tutorial/replicatelist/buildclang.sh",
		"extensions/tutorial/replicatelist/buildgcc.sh",
		"extensions/tutorial/replicatelist/buildvc.bat",
		"extensions/tutorial/replicatelist/buildvc_x64.bat",
		"extensions/tutorial/replicatelist/mylib.c",
		"extensions/tutorial/replicatelist/mylib.ring",
		"extensions/tutorial/replicatelist/README.md",
		"extensions/tutorial/replicatelist/test.ring",
		"extensions/tutorial/sayhello/buildclang.sh",
		"extensions/tutorial/sayhello/buildgcc.sh",
		"extensions/tutorial/sayhello/buildvc.bat",
		"extensions/tutorial/sayhello/buildvc_x64.bat",
		"extensions/tutorial/sayhello/mylib.c",
		"extensions/tutorial/sayhello/mylib.ring",
		"extensions/tutorial/sayhello/README.md",
		"extensions/tutorial/sayhello/test.ring",
		"extensions/tutorial/stringpointer/buildvc.bat",
		"extensions/tutorial/stringpointer/buildvc_x64.bat",
		"extensions/tutorial/stringpointer/mylib.c",
		"extensions/tutorial/stringpointer/README.md",
		"extensions/tutorial/stringpointer/test.ring",
		"extensions/tutorial/stringpointer/test2.ring",
		"extensions/tutorial/sumlist/buildclang.sh",
		"extensions/tutorial/sumlist/buildgcc.sh",
		"extensions/tutorial/sumlist/buildvc.bat",
		"extensions/tutorial/sumlist/buildvc_x64.bat",
		"extensions/tutorial/sumlist/mylib.c",
		"extensions/tutorial/sumlist/mylib.ring",
		"extensions/tutorial/sumlist/README.md",
		"extensions/tutorial/sumlist/test.ring",
		"extensions/tutorial/sumtwonumbers/buildclang.sh",
		"extensions/tutorial/sumtwonumbers/buildgcc.sh",
		"extensions/tutorial/sumtwonumbers/buildvc.bat",
		"extensions/tutorial/sumtwonumbers/buildvc_x64.bat",
		"extensions/tutorial/sumtwonumbers/mylib.c",
		"extensions/tutorial/sumtwonumbers/mylib.ring",
		"extensions/tutorial/sumtwonumbers/README.md",
		"extensions/tutorial/sumtwonumbers/test.ring",
		"extensions/tutorial/updatetable/buildclang.sh",
		"extensions/tutorial/updatetable/buildgcc.sh",
		"extensions/tutorial/updatetable/buildvc.bat",
		"extensions/tutorial/updatetable/buildvc_x64.bat",
		"extensions/tutorial/updatetable/mylib.c",
		"extensions/tutorial/updatetable/mylib.ring",
		"extensions/tutorial/updatetable/README.md",
		"extensions/tutorial/updatetable/test.ring"
	],
	:windowsfiles = 	[

	],
	:linuxfiles = 	[

	],
	:ubuntufiles = 	[

	],
	:fedorafiles = 	[

	],
	:macosfiles = 	[

	],
	:windowsringfolderfiles = 	[

	],
	:linuxringfolderfiles = 	[

	],
	:ubunturingfolderfiles = 	[

	],
	:fedoraringfolderfiles = 	[

	],
	:macosringfolderfiles = 	[

	],
	:run = "ring main.ring",
	:windowsrun = "",
	:linuxrun = "",
	:macosrun = "",
	:ubunturun = "",
	:fedorarun = "",
	:setup = "",
	:windowssetup = "",
	:linuxsetup = "",
	:macossetup = "",
	:ubuntusetup = "",
	:fedorasetup = "",
	:remove = "",
	:windowsremove = "",
	:linuxremove = "",
	:macosremove = "",
	:ubunturemove = "",
	:fedoraremove = "",
	:remotefolder = "extensionstutorials",
	:branch = "master",
	:providerusername = "ringpackages",
	:providerwebsite = "github.com"
]