# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 22:56:52

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new hyperlinkView { win.show() } 
		exec()
	}
}

class hyperlinkView from WindowsViewParent
	win = new qMainWindow() { 
		move(40,78)
		resize(400,400)
		setWindowTitle("HyperLink")
		setstylesheet("background-color:;") 
		HyperLink1 = new label(win) {
			move(45,50)
			resize(223,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText('<a href="http://www.ring-lang.net">Ring Language Website</a>')
			
		}
		HyperLink2 = new label(win) {
			move(38,122)
			resize(199,29)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText('<a href="http://www.pwct.org">Programming Without Coding Technology</a>')
			
		}
	}

# End of the Generated Source Code File...