# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.21 Form Designer
# Date : 02/07/2024
# Time : 01:37:26

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new hyperlinkView { win.show() } 
		exec()
	}
}

class hyperlinkView from WindowsViewParent
	win = new MainWindow() { 
		move(40,78)
		resize(400,374)
		setWindowTitle("HyperLink")
		setstylesheet("background-color:;") 
		HyperLink1 = new label(win) {
			move(38,132)
			resize(309,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText('<a href="http://www.ring-lang.net">Ring Language Website</a>')
			
		}
		HyperLink2 = new label(win) {
			move(38,204)
			resize(309,29)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText('<a href="http://www.pwct.org">Programming Without Coding Technology</a>')
			
		}
	}

# End of the Generated Source Code File...