# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.11 Form Designer
# Date : 17/09/2019
# Time : 20:29:28

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new indexstartView { win.show() } 
		exec()
	}
}

class indexstartView from WindowsViewParent
	win = new MainWindow() { 
		move(23,64)
		resize(400,400)
		setWindowTitle("Index Start")
		setstylesheet("background-color:;") 
		ListWidget1 = new listwidget(win) {
			move(8,10)
			resize(222,159)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			AddItem("one")
			AddItem("two")
			AddItem("three")
			AddItem("four")
			AddItem("five")
			setcurrentItemChangedEvent("")
			setcurrentRowChangedEvent("")
			setcurrentTextChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		Combobox1 = new combobox(win) {
			move(2,184)
			resize(249,36)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			AddItem("one",0)
			AddItem("two",0)
			AddItem("three",0)
			AddItem("four",0)
			AddItem("five",0)
			setactivatedEvent("")
			setcurrentIndexChangedEvent("")
			seteditTextChangedEvent("")
			sethighlightedEvent("")
			
		}
		Button1 = new pushbutton(win) {
			move(12,249)
			resize(202,28)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Selected Item")
			setClickEvent(Method(:getindex))
			setBtnImage(Button1,"")
			
		}
		LineEdit1 = new lineedit(win) {
			move(5,292)
			resize(53,25)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		LineEdit2 = new lineedit(win) {
			move(69,293)
			resize(53,26)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Button2 = new pushbutton(win) {
			move(11,332)
			resize(191,28)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Select First Items")
			setClickEvent(Method(:SelectFirst))
			setBtnImage(Button2,"")
			
		}
	}

# End of the Generated Source Code File...