#!/bin/bash
ring scripts/s28.ring
ring scripts/s60.ring
ring scripts/s61.ring
ring scripts/s62.ring
ring scripts/s63.ring
ring scripts/s64.ring
ring scripts/s65.ring
ring scripts/oop.ring
ring scripts/oop2.ring
ring scripts/oop3.ring
ring scripts/oop4.ring
ring scripts/oop5.ring
ring scripts/oop6.ring
ring scripts/oop7.ring
ring scripts/oop8.ring
ring scripts/oop9.ring
ring scripts/oop10.ring
ring scripts/oop11.ring
ring scripts/oop12.ring
ring scripts/oop13.ring
ring scripts/oop14.ring
ring scripts/oop15.ring
ring scripts/oop16.ring
ring scripts/oop17.ring
ring scripts/oop18.ring
ring scripts/oop19.ring
ring scripts/oop20.ring
ring scripts/oop21.ring
ring scripts/oop22.ring
ring scripts/oop23.ring
ring scripts/oop24.ring
ring scripts/oop25.ring
ring scripts/oop26.ring
ring scripts/oop27.ring
ring scripts/oop28.ring
ring scripts/oop29.ring
ring scripts/oop30.ring
ring scripts/oop31.ring
ring scripts/oop32.ring
ring scripts/oop33.ring
ring scripts/oop34.ring
ring scripts/oop35.ring
ring scripts/oop36.ring
ring scripts/oop37.ring
ring scripts/oop38.ring
ring scripts/oop39.ring
ring scripts/oop40.ring
ring scripts/oop41.ring
ring scripts/oop42.ring
ring scripts/oop43.ring
ring scripts/oop44.ring
ring scripts/oop45.ring
ring scripts/oop46.ring
ring scripts/selfbug.ring
ring scripts/selfininit.ring
ring scripts/subobjs.ring
ring scripts/subobjs2.ring
ring scripts/subobjs3.ring
ring scripts/subobjs4.ring
ring scripts/subobjs5.ring
ring scripts/newinlist.ring
ring scripts/toop1.ring
ring scripts/toop2.ring
ring scripts/toop3.ring
ring scripts/toop4.ring
ring scripts/toop5.ring
ring scripts/toop6.ring
ring scripts/toop7.ring
ring scripts/toop8.ring
ring scripts/toop9.ring
ring scripts/toop10.ring
ring scripts/toop11.ring
ring scripts/string2.ring
ring scripts/comment.ring
ring scripts/commenterror.ring
ring scripts/passbug.ring
ring scripts/passbug2.ring
ring scripts/passbug3.ring
ring scripts/retbug.ring
ring scripts/privatebug.ring
ring scripts/privatebug2.ring
ring scripts/privatebug3.ring
ring scripts/sort.ring
ring scripts/sort2.ring
ring scripts/sort3.ring
ring scripts/emptyfile.ring
ring scripts/emptyfile2.ring
ring scripts/emptyfile3.ring
ring scripts/emptyfile4.ring
ring scripts/evaltest.ring
ring scripts/evalclassbug.ring
ring scripts/evalmem2.ring
ring scripts/evalscope.ring
ring scripts/braceend.ring
ring scripts/braceend2.ring
ring scripts/bitwise.ring
ring scripts/retineval.ring
ring scripts/retfunc.ring
ring scripts/math.ring
ring scripts/newinmethodpara.ring
ring scripts/newinpara.ring
ring scripts/findcrash.ring
ring scripts/initbrace.ring
ring scripts/callinitmethod.ring
ring scripts/callinitmethod2.ring
ring scripts/callinitmethod3.ring
ring scripts/callmethodfromobj.ring
ring scripts/braceerror2.ring
ring scripts/parabracebug.ring
ring scripts/dotbracebug.ring
ring scripts/trybug.ring
ring scripts/forincrash.ring
ring scripts/forinlist.ring
ring scripts/timeforfun.ring
ring scripts/printobj2.ring
ring scripts/insertfirst.ring
ring scripts/ppcrash.ring
ring scripts/ppcrash2.ring
ring scripts/nestednew3.ring
ring scripts/each.ring
ring scripts/retassign.ring
ring scripts/forinstr.ring
ring scripts/happynum.ring
ring scripts/happynum2.ring
ring scripts/addmethod.ring
ring scripts/addmethod2.ring
ring scripts/bracexpreval.ring
ring scripts/objectpointer.ring
ring scripts/double.ring
ring scripts/funcdef.ring
ring scripts/funcdef2.ring
ring scripts/sortlistoneitem.ring
ring scripts/findlistofobjs.ring
ring scripts/sortlistofobjsnative.ring
ring scripts/sortlistofobjsnative2.ring
ring scripts/substrchar.ring
ring scripts/ringsqlite.ring
ring scripts/semicolon.ring
ring scripts/visualvars.ring
ring scripts/bracestart.ring
ring scripts/elseif.ring
ring scripts/testendinif.ring
ring scripts/useend.ring
ring scripts/ifother.ring
ring scripts/switchelse.ring
ring scripts/conflict1.ring
ring scripts/conflict2.ring
ring scripts/conflict3.ring
ring scripts/conflict4.ring
ring scripts/privatemethod.ring
ring scripts/privateattribute.ring
ring scripts/dynamicattr1.ring
ring scripts/dynamicattr2.ring
ring scripts/sortobjscase.ring
ring scripts/findlistofobjs2.ring
ring scripts/ifstylebraces.ring
ring scripts/whilestylebraces.ring
ring scripts/forstylebraces.ring
ring scripts/switchstylebraces.ring
ring scripts/trystylebraces.ring
ring scripts/stylebraces.ring
ring scripts/casetest.ring
ring scripts/deftest.ring
ring scripts/forstyle3.ring
ring scripts/forinstyle3.ring
ring scripts/changekeyword.ring
ring scripts/syntaxbasic.ring
ring scripts/naturaland.ring
ring scripts/syntaxbasic2.ring
ring scripts/changeoperator.ring
ring scripts/naturalplus.ring
ring scripts/changeoperator2.ring
ring scripts/evalinbrace.ring
ring scripts/naturalequal.ring
ring scripts/rangemaxtomin.ring
ring scripts/naturaleval.ring
ring scripts/methodbraceerror.ring
ring scripts/methodbraceerror2.ring
ring scripts/methodbraceerror3.ring
ring scripts/methodbraceerror4.ring
cd scripts
ring usestylebasic.ring
ring usestylesupernova.ring
cd ..
ring scripts/isfunctionclass.ring
ring scripts/handlebraceerror.ring
ring scripts/handlebraceerror2.ring
ring scripts/naturalstring.ring
ring scripts/selfsearch.ring
ring scripts/selfafterclass.ring
ring scripts/selfafterclass2.ring
ring scripts/selfafterclass3.ring
ring scripts/selfselfconflict1.ring
ring scripts/selfselfconflict2.ring
ring scripts/selfselfconflict3.ring
ring scripts/selfselfconflict4.ring
ring scripts/selfselfconflict5.ring
ring scripts/selfselfconflict6.ring
ring scripts/assigncrash.ring
ring scripts/assigncrash2.ring
ring scripts/assigncrash3.ring
ring scripts/assigncrash4.ring
ring scripts/assigncrash5.ring
ring scripts/assigncrash6.ring
ring scripts/braceescape.ring
ring scripts/testconflict.ring
ring scripts/usingthis.ring
ring scripts/returninclassregion.ring
ring scripts/initmethod.ring
ring scripts/dynamicmethods.ring
ring scripts/accesssetget.ring
ring scripts/functionsscope.ring
ring scripts/functionsscope2.ring
ring scripts/type2.ring
ring scripts/tryinsideif.ring
ring scripts/dotcrash.ring
ring scripts/braceinlist.ring
ring scripts/syntaxerror2.ring
ring scripts/t.ring
ring scripts/initsyntaxerror.ring
ring scripts/initinnewbug2.ring
ring scripts/returnscope.ring
ring scripts/returnlistfrommethod.ring
ring scripts/evalbrace.ring
ring scripts/equalobjobj.ring
ring scripts/nullpointer.ring
ring scripts/ptrcmp2.ring
ring scripts/listandstrconversion.ring
ring scripts/objmethodnobraceerror.ring
ring scripts/retselfbyref.ring
ring scripts/passtemplisttoinitmethod.ring 
ring scripts/importinsideif.ring 
ring scripts/liststartinbraces.ring
ring scripts/privateinnew.ring
ring scripts/numbers2bytes.ring
ring scripts/trimerror.ring
ring scripts/anoninhash.ring
ring scripts/bracenewinheritance.ring
ring scripts/nestedfunccall.ring
ring scripts/classbraces.ring
ring scripts/funcbraces.ring
ring scripts/classbraces2.ring
ring scripts/classend.ring
ring scripts/packageend.ring
ring scripts/packagebraces.ring
ring scripts/endfunc.ring
ring scripts/types.ring
ring scripts/inclassregion1.ring 
ring scripts/inclassregion2.ring
ring scripts/inclassregion3.ring
ring scripts/underscoreinnumber.ring
ring scripts/underscoreinnumber2.ring
ring scripts/fafternumber.ring
ring scripts/newtrytest.ring
ring scripts/newtrytest2.ring
ring scripts/manygetter.ring
ring scripts/nosettergetterinclassmethods.ring
ring scripts/privateattributereuse.ring
ring scripts/listnovar.ring
ring scripts/checknull.ring
ring scripts/selfaddcrash.ring
ring scripts/errorloc.ring
ring scripts/rangekeyword.ring
ring scripts/objdecimals.ring
ring scripts/literror.ring
ring scripts/noobject.ring
ring scripts/objcontainslist.ring
ring scripts/loadpackage.ring
ring scripts/testfnicr.ring
ring scripts/testfnicr2.ring
ring scripts/plusequalfunc.ring
ring scripts/varptr.ring
ring scripts/forloopscope.ring
ring scripts/chars.ring
ring scripts/ncemain.ring
ring scripts/filenameinpara.ring
ring scripts/filepath1_linux.ring
ring scripts/ringinring.ring
ring scripts/ignorenewline.ring
ring scripts/thisinclassregion.ring
ring scripts/nullattr.ring
ring scripts/nullptr.ring
