# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 22:57:59

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new radiobuttonView { win.show() } 
		exec()
	}
}

class radiobuttonView from WindowsViewParent
	win = new qMainWindow() { 
		move(55,63)
		resize(400,400)
		setWindowTitle("RadioButton")
		setstylesheet("background-color:;") 
		RadioButton1 = new radiobutton(win) {
			move(22,87)
			resize(123,39)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("One")
			setclickedEvent("")
			setpressedEvent("")
			setreleasedEvent("")
			settoggledEvent("")
			
		}
		RadioButton2 = new radiobutton(win) {
			move(22,156)
			resize(138,33)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Two")
			setclickedEvent("")
			setpressedEvent("")
			setreleasedEvent("")
			settoggledEvent("")
			
		}
		RadioButton3 = new radiobutton(win) {
			move(22,210)
			resize(147,35)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Three")
			setclickedEvent("")
			setpressedEvent("")
			setreleasedEvent("")
			settoggledEvent("")
			
		}
	}

# End of the Generated Source Code File...