# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 23/04/2017
# Time : 14:04:54

Load "stdlib.ring"
Load "guilib.ring"

import formdesigner

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new menubardesignerView { win.show() } 
		exec()
	}
}

package formdesigner

class MenubarDesignerView from WindowsViewParent
	win = new qMainWindow() {
		move(13,15)
		resize(740,575)
		setWindowTitle("Menubar Designer")
		setstylesheet("background-color:;")

		setWindowFlags(Qt_Window | Qt_WindowTitleHint | Qt_WindowCloseButtonHint | Qt_WindowStaysOnTopHint | Qt_CustomizeWindowHint)
		Label1 = new qlabel(win) {
			move(8,24)
			resize(64,27)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Menu Items")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		TreeWidget1 = new qtreewidget(win) {
			move(86,29)
			resize(503,316)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setColumnCount(1)
			oList = new qstringlist() {
				Append("Text")
			}
			setheaderlabels(oList)
			setHeaderHidden(True)
			setcollapsedEvent("")
			setexpandedEvent("")
			setactivatedEvent("")
			setclickedEvent(Method(:ItemClickAction))
			setdoubleClickedEvent("")
			setenteredEvent("")
			setpressedEvent("")
			setviewportEnteredEvent("")
			setcurrentItemChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemCollapsedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemExpandedEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")

		}
		Button1 = new qpushbutton(win) {
			move(595,29)
			resize(129,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("New")
			setClickEvent(Method(:NewAction))
			setBtnImage(Button1,"")

		}
		Button2 = new qpushbutton(win) {
			move(595,73)
			resize(129,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Delete")
			setClickEvent(Method(:DeleteAction))
			setBtnImage(Button2,"")

		}
		Label2 = new qlabel(win) {
			move(9,362)
			resize(63,31)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Text")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		Label3 = new qlabel(win) {
			move(9,403)
			resize(63,33)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Image")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		Label4 = new qlabel(win) {
			move(9,446)
			resize(63,28)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Shortcut")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		Label5 = new qlabel(win) {
			move(9,484)
			resize(63,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Action")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		ItemText = new qlineedit(win) {
			move(86,365)
			resize(503,30)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent(Method(:ItemTextChangeAction))
			setselectionChangedEvent("")
			settextEditedEvent("")

		}
		ItemImage = new qlineedit(win) {
			move(86,405)
			resize(503,30)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent(Method(:ItemImageChangeAction))
			setselectionChangedEvent("")
			settextEditedEvent("")

		}
		ItemShortcut = new qlineedit(win) {
			move(86,445)
			resize(503,30)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent(Method(:ItemShortCutChangeAction))
			setselectionChangedEvent("")
			settextEditedEvent("")

		}
		ItemAction = new qlineedit(win) {
			move(86,485)
			resize(503,30)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent(Method(:ItemActionChangeAction))
			setselectionChangedEvent("")
			settextEditedEvent("")

		}
		Button3 = new qpushbutton(win) {
			move(595,117)
			resize(129,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			setText("Close")
			setClickEvent(Method(:CloseAction))
			setBtnImage(Button3,"")

		}
	}


# End of the Generated Source Code File...
