# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.8 Form Designer
# Date : 06/05/2018
# Time : 16:37:21

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new menubardesignerView { win.show() } 
		exec()
	}
}

class menubardesignerView from WindowsViewParent
	win = new MainWindow() { 
		move(0,0)
		resize(872,722)
		setWindowTitle("Menubar Designer")
		setstylesheet("background-color:#efebe7;") 

		setWindowFlags(Qt_Window | Qt_WindowTitleHint | Qt_WindowCloseButtonHint | Qt_WindowStaysOnTopHint | Qt_CustomizeWindowHint) 
		Label1 = new label(win) {
			move(8,24)
			resize(164,26)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Menu Items")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		TreeWidget1 = new treewidget(win) {
			move(186,29)
			resize(503,316)
			setstylesheet("color:black;background-color:#ffffff;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setColumnCount(1)
			oList = new qstringlist() {
				Append("Text")
			}
			setheaderlabels(oList)
			setHeaderHidden(True)
			setcollapsedEvent("")
			setexpandedEvent("")
			setactivatedEvent("")
			setclickedEvent(Method(:ItemClickAction))
			setdoubleClickedEvent("")
			setenteredEvent("")
			setpressedEvent("")
			setviewportEnteredEvent("")
			setcurrentItemChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemCollapsedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemExpandedEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		Button1 = new pushbutton(win) {
			move(715,29)
			resize(129,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("New")
			setClickEvent(Method(:NewAction))
			setBtnImage(Button1,"")
			
		}
		Button2 = new pushbutton(win) {
			move(715,73)
			resize(129,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Delete")
			setClickEvent(Method(:DeleteAction))
			setBtnImage(Button2,"")
			
		}
		Label2 = new label(win) {
			move(9,362)
			resize(163,31)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Text")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		Label3 = new label(win) {
			move(9,403)
			resize(163,33)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Image")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		Label4 = new label(win) {
			move(9,446)
			resize(163,28)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Shortcut")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		Label5 = new label(win) {
			move(9,484)
			resize(160,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Action")
			setAlignment(Qt_AlignRight |  Qt_AlignVCenter)
		}
		ItemText = new lineedit(win) {
			move(186,365)
			resize(503,30)
			setstylesheet("color:black;background-color:#ffffff;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent(Method(:ItemTextChangeAction))
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		ItemImage = new lineedit(win) {
			move(186,405)
			resize(503,30)
			setstylesheet("color:black;background-color:#ffffff;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent(Method(:ItemImageChangeAction))
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		ItemShortcut = new lineedit(win) {
			move(186,445)
			resize(503,30)
			setstylesheet("color:black;background-color:#ffffff;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent(Method(:ItemShortCutChangeAction))
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		ItemAction = new lineedit(win) {
			move(186,485)
			resize(503,30)
			setstylesheet("color:black;background-color:#ffffff;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent(Method(:ItemActionChangeAction))
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Button3 = new pushbutton(win) {
			move(715,117)
			resize(129,34)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Close")
			setClickEvent(Method(:CloseAction))
			setBtnImage(Button3,"")
			
		}
		Layout1 = new QHBoxLayout() {
			AddWidget(Label1)
			AddWidget(TreeWidget1)
			
		}
		Layout2 = new QHBoxLayout() {
			AddWidget(Label2)
			AddWidget(ItemText)
			
		}
		Layout3 = new QHBoxLayout() {
			AddWidget(Label3)
			AddWidget(ItemImage)
			
		}
		Layout4 = new QHBoxLayout() {
			AddWidget(Label4)
			AddWidget(ItemShortcut)
			
		}
		Layout5 = new QHBoxLayout() {
			AddWidget(Label5)
			AddWidget(ItemAction)
			
		}
		Layout6 = new QVBoxLayout() {
			AddLayout(Layout1)
			AddLayout(Layout2)
			AddLayout(Layout3)
			AddLayout(Layout4)
			AddLayout(Layout5)
			
		}
		Layout7 = new QVBoxLayout() {
			AddWidget(Button1)
			AddWidget(Button2)
			AddWidget(Button3)
			
		}
		Layout8 = new QHBoxLayout() {
			AddLayout(Layout6)
			AddLayout(Layout7)
			
		}

		oMWLayoutWidget = new qWidget() { setLayout(Layout8) }
		setCentralWidget(oMWLayoutWidget) 
	}

# End of the Generated Source Code File...