# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.3 Form Designer
# Date : 13/05/2017
# Time : 22:55:38

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new qApp {
		StyleFusion()
		new datetimeView { win.show() } 
		exec()
	}
}

class datetimeView from WindowsViewParent
	win = new qMainWindow() { 
		move(100,100)
		resize(400,400)
		setWindowTitle("DateTime")
		setstylesheet("background-color:;") 
		Datetimeedit1 = new datetimeedit(win) {
			move(36,50)
			resize(221,42)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("")
			setfont(oFont)
			
		}
	}

# End of the Generated Source Code File...